/*
 * WordPress REST API
 * The WordPress REST API is a powerful part of WordPress that lets you read and write various parts of WordPress data such as posts, pages, users, media, categories, tags, and custom content types defined in the installation.
 *
 * The version of the OpenAPI document: v2
 * Contact: labs@wtx.pl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pl.wtx.wordpress.api.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import pl.wtx.wordpress.api.client.invoker.JSON;

/**
 * BlocktypeVariationsInnerInnerBlocksInner
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class BlocktypeVariationsInnerInnerBlocksInner {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nullable
  private String name;

  public static final String SERIALIZED_NAME_ATTRIBUTES = "attributes";
  @SerializedName(SERIALIZED_NAME_ATTRIBUTES)
  @javax.annotation.Nullable
  private Object attributes;

  public static final String SERIALIZED_NAME_INNER_BLOCKS = "innerBlocks";
  @SerializedName(SERIALIZED_NAME_INNER_BLOCKS)
  @javax.annotation.Nullable
  private List<String> innerBlocks = new ArrayList<>();

  public BlocktypeVariationsInnerInnerBlocksInner() {
  }

  public BlocktypeVariationsInnerInnerBlocksInner name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * The name of the inner block.
   * @return name
   */
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public BlocktypeVariationsInnerInnerBlocksInner attributes(@javax.annotation.Nullable Object attributes) {
    this.attributes = attributes;
    return this;
  }

  /**
   * The attributes of the inner block.
   * @return attributes
   */
  @javax.annotation.Nullable
  public Object getAttributes() {
    return attributes;
  }

  public void setAttributes(@javax.annotation.Nullable Object attributes) {
    this.attributes = attributes;
  }


  public BlocktypeVariationsInnerInnerBlocksInner innerBlocks(@javax.annotation.Nullable List<String> innerBlocks) {
    this.innerBlocks = innerBlocks;
    return this;
  }

  public BlocktypeVariationsInnerInnerBlocksInner addInnerBlocksItem(String innerBlocksItem) {
    if (this.innerBlocks == null) {
      this.innerBlocks = new ArrayList<>();
    }
    this.innerBlocks.add(innerBlocksItem);
    return this;
  }

  /**
   * A list of the inner block&#39;s own inner blocks. This is a recursive definition following the parent innerBlocks schema.
   * @return innerBlocks
   */
  @javax.annotation.Nullable
  public List<String> getInnerBlocks() {
    return innerBlocks;
  }

  public void setInnerBlocks(@javax.annotation.Nullable List<String> innerBlocks) {
    this.innerBlocks = innerBlocks;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BlocktypeVariationsInnerInnerBlocksInner blocktypeVariationsInnerInnerBlocksInner = (BlocktypeVariationsInnerInnerBlocksInner) o;
    return Objects.equals(this.name, blocktypeVariationsInnerInnerBlocksInner.name) &&
        Objects.equals(this.attributes, blocktypeVariationsInnerInnerBlocksInner.attributes) &&
        Objects.equals(this.innerBlocks, blocktypeVariationsInnerInnerBlocksInner.innerBlocks);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, attributes, innerBlocks);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BlocktypeVariationsInnerInnerBlocksInner {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    innerBlocks: ").append(toIndentedString(innerBlocks)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("name");
    openapiFields.add("attributes");
    openapiFields.add("innerBlocks");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to BlocktypeVariationsInnerInnerBlocksInner
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!BlocktypeVariationsInnerInnerBlocksInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in BlocktypeVariationsInnerInnerBlocksInner is not found in the empty JSON string", BlocktypeVariationsInnerInnerBlocksInner.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!BlocktypeVariationsInnerInnerBlocksInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `BlocktypeVariationsInnerInnerBlocksInner` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("innerBlocks") != null && !jsonObj.get("innerBlocks").isJsonNull() && !jsonObj.get("innerBlocks").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `innerBlocks` to be an array in the JSON string but got `%s`", jsonObj.get("innerBlocks").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BlocktypeVariationsInnerInnerBlocksInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BlocktypeVariationsInnerInnerBlocksInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BlocktypeVariationsInnerInnerBlocksInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BlocktypeVariationsInnerInnerBlocksInner.class));

       return (TypeAdapter<T>) new TypeAdapter<BlocktypeVariationsInnerInnerBlocksInner>() {
           @Override
           public void write(JsonWriter out, BlocktypeVariationsInnerInnerBlocksInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public BlocktypeVariationsInnerInnerBlocksInner read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of BlocktypeVariationsInnerInnerBlocksInner given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of BlocktypeVariationsInnerInnerBlocksInner
   * @throws IOException if the JSON string is invalid with respect to BlocktypeVariationsInnerInnerBlocksInner
   */
  public static BlocktypeVariationsInnerInnerBlocksInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BlocktypeVariationsInnerInnerBlocksInner.class);
  }

  /**
   * Convert an instance of BlocktypeVariationsInnerInnerBlocksInner to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

