/*
 * WordPress REST API
 * The WordPress REST API is a powerful part of WordPress that lets you read and write various parts of WordPress data such as posts, pages, users, media, categories, tags, and custom content types defined in the installation.
 *
 * The version of the OpenAPI document: v2
 * Contact: labs@wtx.pl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pl.wtx.wordpress.api.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import pl.wtx.wordpress.api.client.invoker.JSON;

/**
 * BlocktypeStylesInner
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class BlocktypeStylesInner {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nullable
  private String name;

  public static final String SERIALIZED_NAME_LABEL = "label";
  @SerializedName(SERIALIZED_NAME_LABEL)
  @javax.annotation.Nullable
  private String label;

  public static final String SERIALIZED_NAME_INLINE_STYLE = "inline_style";
  @SerializedName(SERIALIZED_NAME_INLINE_STYLE)
  @javax.annotation.Nullable
  private String inlineStyle;

  public static final String SERIALIZED_NAME_STYLE_HANDLE = "style_handle";
  @SerializedName(SERIALIZED_NAME_STYLE_HANDLE)
  @javax.annotation.Nullable
  private String styleHandle;

  public BlocktypeStylesInner() {
  }

  public BlocktypeStylesInner name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Unique name identifying the style.
   * @return name
   */
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public BlocktypeStylesInner label(@javax.annotation.Nullable String label) {
    this.label = label;
    return this;
  }

  /**
   * The human-readable label for the style.
   * @return label
   */
  @javax.annotation.Nullable
  public String getLabel() {
    return label;
  }

  public void setLabel(@javax.annotation.Nullable String label) {
    this.label = label;
  }


  public BlocktypeStylesInner inlineStyle(@javax.annotation.Nullable String inlineStyle) {
    this.inlineStyle = inlineStyle;
    return this;
  }

  /**
   * Inline CSS code that registers the CSS class required for the style.
   * @return inlineStyle
   */
  @javax.annotation.Nullable
  public String getInlineStyle() {
    return inlineStyle;
  }

  public void setInlineStyle(@javax.annotation.Nullable String inlineStyle) {
    this.inlineStyle = inlineStyle;
  }


  public BlocktypeStylesInner styleHandle(@javax.annotation.Nullable String styleHandle) {
    this.styleHandle = styleHandle;
    return this;
  }

  /**
   * Contains the handle that defines the block style.
   * @return styleHandle
   */
  @javax.annotation.Nullable
  public String getStyleHandle() {
    return styleHandle;
  }

  public void setStyleHandle(@javax.annotation.Nullable String styleHandle) {
    this.styleHandle = styleHandle;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BlocktypeStylesInner blocktypeStylesInner = (BlocktypeStylesInner) o;
    return Objects.equals(this.name, blocktypeStylesInner.name) &&
        Objects.equals(this.label, blocktypeStylesInner.label) &&
        Objects.equals(this.inlineStyle, blocktypeStylesInner.inlineStyle) &&
        Objects.equals(this.styleHandle, blocktypeStylesInner.styleHandle);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, label, inlineStyle, styleHandle);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BlocktypeStylesInner {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    inlineStyle: ").append(toIndentedString(inlineStyle)).append("\n");
    sb.append("    styleHandle: ").append(toIndentedString(styleHandle)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("name");
    openapiFields.add("label");
    openapiFields.add("inline_style");
    openapiFields.add("style_handle");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to BlocktypeStylesInner
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!BlocktypeStylesInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in BlocktypeStylesInner is not found in the empty JSON string", BlocktypeStylesInner.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!BlocktypeStylesInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `BlocktypeStylesInner` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("label") != null && !jsonObj.get("label").isJsonNull()) && !jsonObj.get("label").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `label` to be a primitive type in the JSON string but got `%s`", jsonObj.get("label").toString()));
      }
      if ((jsonObj.get("inline_style") != null && !jsonObj.get("inline_style").isJsonNull()) && !jsonObj.get("inline_style").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `inline_style` to be a primitive type in the JSON string but got `%s`", jsonObj.get("inline_style").toString()));
      }
      if ((jsonObj.get("style_handle") != null && !jsonObj.get("style_handle").isJsonNull()) && !jsonObj.get("style_handle").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `style_handle` to be a primitive type in the JSON string but got `%s`", jsonObj.get("style_handle").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BlocktypeStylesInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BlocktypeStylesInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BlocktypeStylesInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BlocktypeStylesInner.class));

       return (TypeAdapter<T>) new TypeAdapter<BlocktypeStylesInner>() {
           @Override
           public void write(JsonWriter out, BlocktypeStylesInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public BlocktypeStylesInner read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of BlocktypeStylesInner given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of BlocktypeStylesInner
   * @throws IOException if the JSON string is invalid with respect to BlocktypeStylesInner
   */
  public static BlocktypeStylesInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BlocktypeStylesInner.class);
  }

  /**
   * Convert an instance of BlocktypeStylesInner to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

