/*
 * WordPress REST API
 * The WordPress REST API is a powerful part of WordPress that lets you read and write various parts of WordPress data such as posts, pages, users, media, categories, tags, and custom content types defined in the installation.
 *
 * The version of the OpenAPI document: v2
 * Contact: labs@wtx.pl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pl.wtx.wordpress.api.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import pl.wtx.wordpress.api.client.invoker.JSON;

/**
 * Meta fields.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class CommentsPostRequestMeta {
  /**
   * Note resolution status
   */
  @JsonAdapter(WpNoteStatusEnum.Adapter.class)
  public enum WpNoteStatusEnum {
    RESOLVED("resolved"),
    
    REOPEN("reopen");

    private String value;

    WpNoteStatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static WpNoteStatusEnum fromValue(String value) {
      for (WpNoteStatusEnum b : WpNoteStatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<WpNoteStatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final WpNoteStatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public WpNoteStatusEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return WpNoteStatusEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      WpNoteStatusEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_WP_NOTE_STATUS = "_wp_note_status";
  @SerializedName(SERIALIZED_NAME_WP_NOTE_STATUS)
  @javax.annotation.Nullable
  private WpNoteStatusEnum wpNoteStatus;

  public CommentsPostRequestMeta() {
  }

  public CommentsPostRequestMeta wpNoteStatus(@javax.annotation.Nullable WpNoteStatusEnum wpNoteStatus) {
    this.wpNoteStatus = wpNoteStatus;
    return this;
  }

  /**
   * Note resolution status
   * @return wpNoteStatus
   */
  @javax.annotation.Nullable
  public WpNoteStatusEnum getWpNoteStatus() {
    return wpNoteStatus;
  }

  public void setWpNoteStatus(@javax.annotation.Nullable WpNoteStatusEnum wpNoteStatus) {
    this.wpNoteStatus = wpNoteStatus;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CommentsPostRequestMeta commentsPostRequestMeta = (CommentsPostRequestMeta) o;
    return Objects.equals(this.wpNoteStatus, commentsPostRequestMeta.wpNoteStatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(wpNoteStatus);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CommentsPostRequestMeta {\n");
    sb.append("    wpNoteStatus: ").append(toIndentedString(wpNoteStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("_wp_note_status");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CommentsPostRequestMeta
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CommentsPostRequestMeta.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CommentsPostRequestMeta is not found in the empty JSON string", CommentsPostRequestMeta.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CommentsPostRequestMeta.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CommentsPostRequestMeta` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("_wp_note_status") != null && !jsonObj.get("_wp_note_status").isJsonNull()) && !jsonObj.get("_wp_note_status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `_wp_note_status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("_wp_note_status").toString()));
      }
      // validate the optional field `_wp_note_status`
      if (jsonObj.get("_wp_note_status") != null && !jsonObj.get("_wp_note_status").isJsonNull()) {
        WpNoteStatusEnum.validateJsonElement(jsonObj.get("_wp_note_status"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CommentsPostRequestMeta.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CommentsPostRequestMeta' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CommentsPostRequestMeta> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CommentsPostRequestMeta.class));

       return (TypeAdapter<T>) new TypeAdapter<CommentsPostRequestMeta>() {
           @Override
           public void write(JsonWriter out, CommentsPostRequestMeta value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CommentsPostRequestMeta read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CommentsPostRequestMeta given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CommentsPostRequestMeta
   * @throws IOException if the JSON string is invalid with respect to CommentsPostRequestMeta
   */
  public static CommentsPostRequestMeta fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CommentsPostRequestMeta.class);
  }

  /**
   * Convert an instance of CommentsPostRequestMeta to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

