/*
 * WordPress REST API
 * The WordPress REST API is a powerful part of WordPress that lets you read and write various parts of WordPress data such as posts, pages, users, media, categories, tags, and custom content types defined in the installation.
 *
 * The version of the OpenAPI document: v2
 * Contact: labs@wtx.pl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pl.wtx.wordpress.api.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import pl.wtx.wordpress.api.client.model.TermIDTaxonomyQuery;



import java.io.IOException;
import java.lang.reflect.Type;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.JsonPrimitive;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonSerializationContext;
import com.google.gson.JsonSerializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonArray;
import com.google.gson.JsonParseException;

import pl.wtx.wordpress.api.client.invoker.JSON;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class PostsGetCategoriesParameter extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(PostsGetCategoriesParameter.class.getName());

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!PostsGetCategoriesParameter.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'PostsGetCategoriesParameter' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);

            final Type typeInstanceListInteger = new TypeToken<List<Integer>>(){}.getType();
            final TypeAdapter<List<Integer>> adapterListInteger = (TypeAdapter<List<Integer>>) gson.getDelegateAdapter(this, TypeToken.get(typeInstanceListInteger));
            final TypeAdapter<TermIDTaxonomyQuery> adapterTermIDTaxonomyQuery = gson.getDelegateAdapter(this, TypeToken.get(TermIDTaxonomyQuery.class));

            return (TypeAdapter<T>) new TypeAdapter<PostsGetCategoriesParameter>() {
                @Override
                public void write(JsonWriter out, PostsGetCategoriesParameter value) throws IOException {
                    if (value == null || value.getActualInstance() == null) {
                        elementAdapter.write(out, null);
                        return;
                    }

                    // check if the actual instance is of the type `List<Integer>`
                    if (value.getActualInstance() instanceof List<?>) {
                        JsonPrimitive primitive = adapterListInteger.toJsonTree((List<Integer>)value.getActualInstance()).getAsJsonPrimitive();
                        elementAdapter.write(out, primitive);
                        return;
                    }
                    // check if the actual instance is of the type `TermIDTaxonomyQuery`
                    if (value.getActualInstance() instanceof TermIDTaxonomyQuery) {
                        JsonElement element = adapterTermIDTaxonomyQuery.toJsonTree((TermIDTaxonomyQuery)value.getActualInstance());
                        elementAdapter.write(out, element);
                        return;
                    }
                    throw new IOException("Failed to serialize as the type doesn't match oneOf schemas: List<Integer>, TermIDTaxonomyQuery");
                }

                @Override
                public PostsGetCategoriesParameter read(JsonReader in) throws IOException {
                    Object deserialized = null;
                    JsonElement jsonElement = elementAdapter.read(in);

                    int match = 0;
                    ArrayList<String> errorMessages = new ArrayList<>();
                    TypeAdapter actualAdapter = elementAdapter;

                    // deserialize List<Integer>
                    try {
                        // validate the JSON object to see if any exception is thrown
                        if (!jsonElement.isJsonArray()) {
                            throw new IllegalArgumentException(String.format("Expected json element to be a array type in the JSON string but got `%s`", jsonElement.toString()));
                        }

                        JsonArray array = jsonElement.getAsJsonArray();
                        // validate array items
                        for(JsonElement element : array) {
                            if (!element.getAsJsonPrimitive().isNumber()) {
                                throw new IllegalArgumentException(String.format("Expected array items to be of type Number in the JSON string but got `%s`", jsonElement.toString()));
                            }
                        }
                        actualAdapter = adapterListInteger;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'List<Integer>'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for List<Integer> failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'List<Integer>'", e);
                    }
                    // deserialize TermIDTaxonomyQuery
                    try {
                        // validate the JSON object to see if any exception is thrown
                        TermIDTaxonomyQuery.validateJsonElement(jsonElement);
                        actualAdapter = adapterTermIDTaxonomyQuery;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'TermIDTaxonomyQuery'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for TermIDTaxonomyQuery failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'TermIDTaxonomyQuery'", e);
                    }

                    if (match == 1) {
                        PostsGetCategoriesParameter ret = new PostsGetCategoriesParameter();
                        ret.setActualInstance(actualAdapter.fromJsonTree(jsonElement));
                        return ret;
                    }

                    throw new IOException(String.format("Failed deserialization for PostsGetCategoriesParameter: %d classes match result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", match, errorMessages, jsonElement.toString()));
                }
            }.nullSafe();
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, Class<?>> schemas = new HashMap<String, Class<?>>();

    public PostsGetCategoriesParameter() {
        super("oneOf", Boolean.FALSE);
    }

    public PostsGetCategoriesParameter(Object o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("List<Integer>", List.class);
        schemas.put("TermIDTaxonomyQuery", TermIDTaxonomyQuery.class);
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return PostsGetCategoriesParameter.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * List<Integer>, TermIDTaxonomyQuery
     *
     * It could be an instance of the 'oneOf' schemas.
     */
    @Override
    public void setActualInstance(Object instance) {
        if (instance instanceof List<?>) {
            List<?> list = (List<?>) instance;
            if (list.get(0) instanceof Integer) {
                super.setActualInstance(instance);
                return;
            }
        }

        if (instance instanceof TermIDTaxonomyQuery) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be List<Integer>, TermIDTaxonomyQuery");
    }

    /**
     * Get the actual instance, which can be the following:
     * List<Integer>, TermIDTaxonomyQuery
     *
     * @return The actual instance (List<Integer>, TermIDTaxonomyQuery)
     */
    @SuppressWarnings("unchecked")
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `List<Integer>`. If the actual instance is not `List<Integer>`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `List<Integer>`
     * @throws ClassCastException if the instance is not `List<Integer>`
     */
    public List<Integer> getListInteger() throws ClassCastException {
        return (List<Integer>)super.getActualInstance();
    }

    /**
     * Get the actual instance of `TermIDTaxonomyQuery`. If the actual instance is not `TermIDTaxonomyQuery`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `TermIDTaxonomyQuery`
     * @throws ClassCastException if the instance is not `TermIDTaxonomyQuery`
     */
    public TermIDTaxonomyQuery getTermIDTaxonomyQuery() throws ClassCastException {
        return (TermIDTaxonomyQuery)super.getActualInstance();
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to PostsGetCategoriesParameter
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        // validate oneOf schemas one by one
        int validCount = 0;
        ArrayList<String> errorMessages = new ArrayList<>();
        // validate the json string with List<Integer>
        try {
            if (!jsonElement.isJsonArray()) {
                throw new IllegalArgumentException(String.format("Expected json element to be a array type in the JSON string but got `%s`", jsonElement.toString()));
            }
            JsonArray array = jsonElement.getAsJsonArray();
            // validate array items
            for(JsonElement element : array) {
                if (!element.getAsJsonPrimitive().isNumber()) {
                    throw new IllegalArgumentException(String.format("Expected array items to be of type Number in the JSON string but got `%s`", jsonElement.toString()));
                }
            }
            validCount++;
        } catch (Exception e) {
            errorMessages.add(String.format("Deserialization for List<Integer> failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        // validate the json string with TermIDTaxonomyQuery
        try {
            TermIDTaxonomyQuery.validateJsonElement(jsonElement);
            validCount++;
        } catch (Exception e) {
            errorMessages.add(String.format("Deserialization for TermIDTaxonomyQuery failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        if (validCount != 1) {
            throw new IOException(String.format("The JSON string is invalid for PostsGetCategoriesParameter with oneOf schemas: List<Integer>, TermIDTaxonomyQuery. %d class(es) match the result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", validCount, errorMessages, jsonElement.toString()));
        }
    }

    /**
     * Create an instance of PostsGetCategoriesParameter given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of PostsGetCategoriesParameter
     * @throws IOException if the JSON string is invalid with respect to PostsGetCategoriesParameter
     */
    public static PostsGetCategoriesParameter fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, PostsGetCategoriesParameter.class);
    }

    /**
     * Convert an instance of PostsGetCategoriesParameter to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}

