/*
 * WordPress REST API
 * The WordPress REST API is a powerful part of WordPress that lets you read and write various parts of WordPress data such as posts, pages, users, media, categories, tags, and custom content types defined in the installation.
 *
 * The version of the OpenAPI document: v2
 * Contact: labs@wtx.pl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pl.wtx.wordpress.api.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import pl.wtx.wordpress.api.client.invoker.JSON;

/**
 * The visibility settings for the post type.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class RestposttypeVisibility {
  public static final String SERIALIZED_NAME_SHOW_UI = "show_ui";
  @SerializedName(SERIALIZED_NAME_SHOW_UI)
  @javax.annotation.Nullable
  private Boolean showUi;

  public static final String SERIALIZED_NAME_SHOW_IN_NAV_MENUS = "show_in_nav_menus";
  @SerializedName(SERIALIZED_NAME_SHOW_IN_NAV_MENUS)
  @javax.annotation.Nullable
  private Boolean showInNavMenus;

  public RestposttypeVisibility() {
  }

  public RestposttypeVisibility showUi(@javax.annotation.Nullable Boolean showUi) {
    this.showUi = showUi;
    return this;
  }

  /**
   * Whether to generate a default UI for managing this post type.
   * @return showUi
   */
  @javax.annotation.Nullable
  public Boolean getShowUi() {
    return showUi;
  }

  public void setShowUi(@javax.annotation.Nullable Boolean showUi) {
    this.showUi = showUi;
  }


  public RestposttypeVisibility showInNavMenus(@javax.annotation.Nullable Boolean showInNavMenus) {
    this.showInNavMenus = showInNavMenus;
    return this;
  }

  /**
   * Whether to make the post type available for selection in navigation menus.
   * @return showInNavMenus
   */
  @javax.annotation.Nullable
  public Boolean getShowInNavMenus() {
    return showInNavMenus;
  }

  public void setShowInNavMenus(@javax.annotation.Nullable Boolean showInNavMenus) {
    this.showInNavMenus = showInNavMenus;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RestposttypeVisibility restposttypeVisibility = (RestposttypeVisibility) o;
    return Objects.equals(this.showUi, restposttypeVisibility.showUi) &&
        Objects.equals(this.showInNavMenus, restposttypeVisibility.showInNavMenus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(showUi, showInNavMenus);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RestposttypeVisibility {\n");
    sb.append("    showUi: ").append(toIndentedString(showUi)).append("\n");
    sb.append("    showInNavMenus: ").append(toIndentedString(showInNavMenus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("show_ui");
    openapiFields.add("show_in_nav_menus");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to RestposttypeVisibility
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!RestposttypeVisibility.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in RestposttypeVisibility is not found in the empty JSON string", RestposttypeVisibility.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!RestposttypeVisibility.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `RestposttypeVisibility` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!RestposttypeVisibility.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'RestposttypeVisibility' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<RestposttypeVisibility> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(RestposttypeVisibility.class));

       return (TypeAdapter<T>) new TypeAdapter<RestposttypeVisibility>() {
           @Override
           public void write(JsonWriter out, RestposttypeVisibility value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public RestposttypeVisibility read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of RestposttypeVisibility given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of RestposttypeVisibility
   * @throws IOException if the JSON string is invalid with respect to RestposttypeVisibility
   */
  public static RestposttypeVisibility fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, RestposttypeVisibility.class);
  }

  /**
   * Convert an instance of RestposttypeVisibility to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

