/*
 * WordPress REST API
 * The WordPress REST API is a powerful part of WordPress that lets you read and write various parts of WordPress data such as posts, pages, users, media, categories, tags, and custom content types defined in the installation.
 *
 * The version of the OpenAPI document: v2
 * Contact: labs@wtx.pl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pl.wtx.wordpress.api.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.net.URI;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import pl.wtx.wordpress.api.client.invoker.JSON;

/**
 * Settings
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class Settings {
  public static final String SERIALIZED_NAME_TITLE = "title";
  @SerializedName(SERIALIZED_NAME_TITLE)
  @javax.annotation.Nullable
  private String title;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  @javax.annotation.Nullable
  private String description;

  public static final String SERIALIZED_NAME_URL = "url";
  @SerializedName(SERIALIZED_NAME_URL)
  @javax.annotation.Nullable
  private URI url;

  public static final String SERIALIZED_NAME_EMAIL = "email";
  @SerializedName(SERIALIZED_NAME_EMAIL)
  @javax.annotation.Nullable
  private String email;

  public static final String SERIALIZED_NAME_TIMEZONE = "timezone";
  @SerializedName(SERIALIZED_NAME_TIMEZONE)
  @javax.annotation.Nullable
  private String timezone;

  public static final String SERIALIZED_NAME_DATE_FORMAT = "date_format";
  @SerializedName(SERIALIZED_NAME_DATE_FORMAT)
  @javax.annotation.Nullable
  private String dateFormat;

  public static final String SERIALIZED_NAME_TIME_FORMAT = "time_format";
  @SerializedName(SERIALIZED_NAME_TIME_FORMAT)
  @javax.annotation.Nullable
  private String timeFormat;

  public static final String SERIALIZED_NAME_START_OF_WEEK = "start_of_week";
  @SerializedName(SERIALIZED_NAME_START_OF_WEEK)
  @javax.annotation.Nullable
  private Integer startOfWeek;

  public static final String SERIALIZED_NAME_LANGUAGE = "language";
  @SerializedName(SERIALIZED_NAME_LANGUAGE)
  @javax.annotation.Nullable
  private String language = "en_US";

  public static final String SERIALIZED_NAME_USE_SMILIES = "use_smilies";
  @SerializedName(SERIALIZED_NAME_USE_SMILIES)
  @javax.annotation.Nullable
  private Boolean useSmilies = true;

  public static final String SERIALIZED_NAME_DEFAULT_CATEGORY = "default_category";
  @SerializedName(SERIALIZED_NAME_DEFAULT_CATEGORY)
  @javax.annotation.Nullable
  private Integer defaultCategory;

  public static final String SERIALIZED_NAME_DEFAULT_POST_FORMAT = "default_post_format";
  @SerializedName(SERIALIZED_NAME_DEFAULT_POST_FORMAT)
  @javax.annotation.Nullable
  private String defaultPostFormat;

  public static final String SERIALIZED_NAME_POSTS_PER_PAGE = "posts_per_page";
  @SerializedName(SERIALIZED_NAME_POSTS_PER_PAGE)
  @javax.annotation.Nullable
  private Integer postsPerPage = 10;

  public static final String SERIALIZED_NAME_SHOW_ON_FRONT = "show_on_front";
  @SerializedName(SERIALIZED_NAME_SHOW_ON_FRONT)
  @javax.annotation.Nullable
  private String showOnFront;

  public static final String SERIALIZED_NAME_PAGE_ON_FRONT = "page_on_front";
  @SerializedName(SERIALIZED_NAME_PAGE_ON_FRONT)
  @javax.annotation.Nullable
  private Integer pageOnFront;

  public static final String SERIALIZED_NAME_PAGE_FOR_POSTS = "page_for_posts";
  @SerializedName(SERIALIZED_NAME_PAGE_FOR_POSTS)
  @javax.annotation.Nullable
  private Integer pageForPosts;

  /**
   * Allow link notifications from other blogs (pingbacks and trackbacks) on new articles.
   */
  @JsonAdapter(DefaultPingStatusEnum.Adapter.class)
  public enum DefaultPingStatusEnum {
    OPEN("open"),
    
    CLOSED("closed");

    private String value;

    DefaultPingStatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static DefaultPingStatusEnum fromValue(String value) {
      for (DefaultPingStatusEnum b : DefaultPingStatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<DefaultPingStatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final DefaultPingStatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public DefaultPingStatusEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return DefaultPingStatusEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      DefaultPingStatusEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_DEFAULT_PING_STATUS = "default_ping_status";
  @SerializedName(SERIALIZED_NAME_DEFAULT_PING_STATUS)
  @javax.annotation.Nullable
  private DefaultPingStatusEnum defaultPingStatus;

  /**
   * Allow people to submit comments on new posts.
   */
  @JsonAdapter(DefaultCommentStatusEnum.Adapter.class)
  public enum DefaultCommentStatusEnum {
    OPEN("open"),
    
    CLOSED("closed");

    private String value;

    DefaultCommentStatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static DefaultCommentStatusEnum fromValue(String value) {
      for (DefaultCommentStatusEnum b : DefaultCommentStatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<DefaultCommentStatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final DefaultCommentStatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public DefaultCommentStatusEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return DefaultCommentStatusEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      DefaultCommentStatusEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_DEFAULT_COMMENT_STATUS = "default_comment_status";
  @SerializedName(SERIALIZED_NAME_DEFAULT_COMMENT_STATUS)
  @javax.annotation.Nullable
  private DefaultCommentStatusEnum defaultCommentStatus;

  public static final String SERIALIZED_NAME_SITE_LOGO = "site_logo";
  @SerializedName(SERIALIZED_NAME_SITE_LOGO)
  @javax.annotation.Nullable
  private Integer siteLogo;

  public static final String SERIALIZED_NAME_SITE_ICON = "site_icon";
  @SerializedName(SERIALIZED_NAME_SITE_ICON)
  @javax.annotation.Nullable
  private Integer siteIcon;

  public Settings() {
  }

  public Settings title(@javax.annotation.Nullable String title) {
    this.title = title;
    return this;
  }

  /**
   * Site title.
   * @return title
   */
  @javax.annotation.Nullable
  public String getTitle() {
    return title;
  }

  public void setTitle(@javax.annotation.Nullable String title) {
    this.title = title;
  }


  public Settings description(@javax.annotation.Nullable String description) {
    this.description = description;
    return this;
  }

  /**
   * Site tagline.
   * @return description
   */
  @javax.annotation.Nullable
  public String getDescription() {
    return description;
  }

  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }


  public Settings url(@javax.annotation.Nullable URI url) {
    this.url = url;
    return this;
  }

  /**
   * Site URL.
   * @return url
   */
  @javax.annotation.Nullable
  public URI getUrl() {
    return url;
  }

  public void setUrl(@javax.annotation.Nullable URI url) {
    this.url = url;
  }


  public Settings email(@javax.annotation.Nullable String email) {
    this.email = email;
    return this;
  }

  /**
   * This address is used for admin purposes, like new user notification.
   * @return email
   */
  @javax.annotation.Nullable
  public String getEmail() {
    return email;
  }

  public void setEmail(@javax.annotation.Nullable String email) {
    this.email = email;
  }


  public Settings timezone(@javax.annotation.Nullable String timezone) {
    this.timezone = timezone;
    return this;
  }

  /**
   * A city in the same timezone as you.
   * @return timezone
   */
  @javax.annotation.Nullable
  public String getTimezone() {
    return timezone;
  }

  public void setTimezone(@javax.annotation.Nullable String timezone) {
    this.timezone = timezone;
  }


  public Settings dateFormat(@javax.annotation.Nullable String dateFormat) {
    this.dateFormat = dateFormat;
    return this;
  }

  /**
   * A date format for all date strings.
   * @return dateFormat
   */
  @javax.annotation.Nullable
  public String getDateFormat() {
    return dateFormat;
  }

  public void setDateFormat(@javax.annotation.Nullable String dateFormat) {
    this.dateFormat = dateFormat;
  }


  public Settings timeFormat(@javax.annotation.Nullable String timeFormat) {
    this.timeFormat = timeFormat;
    return this;
  }

  /**
   * A time format for all time strings.
   * @return timeFormat
   */
  @javax.annotation.Nullable
  public String getTimeFormat() {
    return timeFormat;
  }

  public void setTimeFormat(@javax.annotation.Nullable String timeFormat) {
    this.timeFormat = timeFormat;
  }


  public Settings startOfWeek(@javax.annotation.Nullable Integer startOfWeek) {
    this.startOfWeek = startOfWeek;
    return this;
  }

  /**
   * A day number of the week that the week should start on.
   * @return startOfWeek
   */
  @javax.annotation.Nullable
  public Integer getStartOfWeek() {
    return startOfWeek;
  }

  public void setStartOfWeek(@javax.annotation.Nullable Integer startOfWeek) {
    this.startOfWeek = startOfWeek;
  }


  public Settings language(@javax.annotation.Nullable String language) {
    this.language = language;
    return this;
  }

  /**
   * WordPress locale code.
   * @return language
   */
  @javax.annotation.Nullable
  public String getLanguage() {
    return language;
  }

  public void setLanguage(@javax.annotation.Nullable String language) {
    this.language = language;
  }


  public Settings useSmilies(@javax.annotation.Nullable Boolean useSmilies) {
    this.useSmilies = useSmilies;
    return this;
  }

  /**
   * Convert emoticons like :-) and :-P to graphics on display.
   * @return useSmilies
   */
  @javax.annotation.Nullable
  public Boolean getUseSmilies() {
    return useSmilies;
  }

  public void setUseSmilies(@javax.annotation.Nullable Boolean useSmilies) {
    this.useSmilies = useSmilies;
  }


  public Settings defaultCategory(@javax.annotation.Nullable Integer defaultCategory) {
    this.defaultCategory = defaultCategory;
    return this;
  }

  /**
   * Default post category.
   * @return defaultCategory
   */
  @javax.annotation.Nullable
  public Integer getDefaultCategory() {
    return defaultCategory;
  }

  public void setDefaultCategory(@javax.annotation.Nullable Integer defaultCategory) {
    this.defaultCategory = defaultCategory;
  }


  public Settings defaultPostFormat(@javax.annotation.Nullable String defaultPostFormat) {
    this.defaultPostFormat = defaultPostFormat;
    return this;
  }

  /**
   * Default post format.
   * @return defaultPostFormat
   */
  @javax.annotation.Nullable
  public String getDefaultPostFormat() {
    return defaultPostFormat;
  }

  public void setDefaultPostFormat(@javax.annotation.Nullable String defaultPostFormat) {
    this.defaultPostFormat = defaultPostFormat;
  }


  public Settings postsPerPage(@javax.annotation.Nullable Integer postsPerPage) {
    this.postsPerPage = postsPerPage;
    return this;
  }

  /**
   * Blog pages show at most.
   * @return postsPerPage
   */
  @javax.annotation.Nullable
  public Integer getPostsPerPage() {
    return postsPerPage;
  }

  public void setPostsPerPage(@javax.annotation.Nullable Integer postsPerPage) {
    this.postsPerPage = postsPerPage;
  }


  public Settings showOnFront(@javax.annotation.Nullable String showOnFront) {
    this.showOnFront = showOnFront;
    return this;
  }

  /**
   * What to show on the front page
   * @return showOnFront
   */
  @javax.annotation.Nullable
  public String getShowOnFront() {
    return showOnFront;
  }

  public void setShowOnFront(@javax.annotation.Nullable String showOnFront) {
    this.showOnFront = showOnFront;
  }


  public Settings pageOnFront(@javax.annotation.Nullable Integer pageOnFront) {
    this.pageOnFront = pageOnFront;
    return this;
  }

  /**
   * The ID of the page that should be displayed on the front page
   * @return pageOnFront
   */
  @javax.annotation.Nullable
  public Integer getPageOnFront() {
    return pageOnFront;
  }

  public void setPageOnFront(@javax.annotation.Nullable Integer pageOnFront) {
    this.pageOnFront = pageOnFront;
  }


  public Settings pageForPosts(@javax.annotation.Nullable Integer pageForPosts) {
    this.pageForPosts = pageForPosts;
    return this;
  }

  /**
   * The ID of the page that should display the latest posts
   * @return pageForPosts
   */
  @javax.annotation.Nullable
  public Integer getPageForPosts() {
    return pageForPosts;
  }

  public void setPageForPosts(@javax.annotation.Nullable Integer pageForPosts) {
    this.pageForPosts = pageForPosts;
  }


  public Settings defaultPingStatus(@javax.annotation.Nullable DefaultPingStatusEnum defaultPingStatus) {
    this.defaultPingStatus = defaultPingStatus;
    return this;
  }

  /**
   * Allow link notifications from other blogs (pingbacks and trackbacks) on new articles.
   * @return defaultPingStatus
   */
  @javax.annotation.Nullable
  public DefaultPingStatusEnum getDefaultPingStatus() {
    return defaultPingStatus;
  }

  public void setDefaultPingStatus(@javax.annotation.Nullable DefaultPingStatusEnum defaultPingStatus) {
    this.defaultPingStatus = defaultPingStatus;
  }


  public Settings defaultCommentStatus(@javax.annotation.Nullable DefaultCommentStatusEnum defaultCommentStatus) {
    this.defaultCommentStatus = defaultCommentStatus;
    return this;
  }

  /**
   * Allow people to submit comments on new posts.
   * @return defaultCommentStatus
   */
  @javax.annotation.Nullable
  public DefaultCommentStatusEnum getDefaultCommentStatus() {
    return defaultCommentStatus;
  }

  public void setDefaultCommentStatus(@javax.annotation.Nullable DefaultCommentStatusEnum defaultCommentStatus) {
    this.defaultCommentStatus = defaultCommentStatus;
  }


  public Settings siteLogo(@javax.annotation.Nullable Integer siteLogo) {
    this.siteLogo = siteLogo;
    return this;
  }

  /**
   * Site logo.
   * @return siteLogo
   */
  @javax.annotation.Nullable
  public Integer getSiteLogo() {
    return siteLogo;
  }

  public void setSiteLogo(@javax.annotation.Nullable Integer siteLogo) {
    this.siteLogo = siteLogo;
  }


  public Settings siteIcon(@javax.annotation.Nullable Integer siteIcon) {
    this.siteIcon = siteIcon;
    return this;
  }

  /**
   * Site icon.
   * @return siteIcon
   */
  @javax.annotation.Nullable
  public Integer getSiteIcon() {
    return siteIcon;
  }

  public void setSiteIcon(@javax.annotation.Nullable Integer siteIcon) {
    this.siteIcon = siteIcon;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Settings settings = (Settings) o;
    return Objects.equals(this.title, settings.title) &&
        Objects.equals(this.description, settings.description) &&
        Objects.equals(this.url, settings.url) &&
        Objects.equals(this.email, settings.email) &&
        Objects.equals(this.timezone, settings.timezone) &&
        Objects.equals(this.dateFormat, settings.dateFormat) &&
        Objects.equals(this.timeFormat, settings.timeFormat) &&
        Objects.equals(this.startOfWeek, settings.startOfWeek) &&
        Objects.equals(this.language, settings.language) &&
        Objects.equals(this.useSmilies, settings.useSmilies) &&
        Objects.equals(this.defaultCategory, settings.defaultCategory) &&
        Objects.equals(this.defaultPostFormat, settings.defaultPostFormat) &&
        Objects.equals(this.postsPerPage, settings.postsPerPage) &&
        Objects.equals(this.showOnFront, settings.showOnFront) &&
        Objects.equals(this.pageOnFront, settings.pageOnFront) &&
        Objects.equals(this.pageForPosts, settings.pageForPosts) &&
        Objects.equals(this.defaultPingStatus, settings.defaultPingStatus) &&
        Objects.equals(this.defaultCommentStatus, settings.defaultCommentStatus) &&
        Objects.equals(this.siteLogo, settings.siteLogo) &&
        Objects.equals(this.siteIcon, settings.siteIcon);
  }

  @Override
  public int hashCode() {
    return Objects.hash(title, description, url, email, timezone, dateFormat, timeFormat, startOfWeek, language, useSmilies, defaultCategory, defaultPostFormat, postsPerPage, showOnFront, pageOnFront, pageForPosts, defaultPingStatus, defaultCommentStatus, siteLogo, siteIcon);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Settings {\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    timezone: ").append(toIndentedString(timezone)).append("\n");
    sb.append("    dateFormat: ").append(toIndentedString(dateFormat)).append("\n");
    sb.append("    timeFormat: ").append(toIndentedString(timeFormat)).append("\n");
    sb.append("    startOfWeek: ").append(toIndentedString(startOfWeek)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    useSmilies: ").append(toIndentedString(useSmilies)).append("\n");
    sb.append("    defaultCategory: ").append(toIndentedString(defaultCategory)).append("\n");
    sb.append("    defaultPostFormat: ").append(toIndentedString(defaultPostFormat)).append("\n");
    sb.append("    postsPerPage: ").append(toIndentedString(postsPerPage)).append("\n");
    sb.append("    showOnFront: ").append(toIndentedString(showOnFront)).append("\n");
    sb.append("    pageOnFront: ").append(toIndentedString(pageOnFront)).append("\n");
    sb.append("    pageForPosts: ").append(toIndentedString(pageForPosts)).append("\n");
    sb.append("    defaultPingStatus: ").append(toIndentedString(defaultPingStatus)).append("\n");
    sb.append("    defaultCommentStatus: ").append(toIndentedString(defaultCommentStatus)).append("\n");
    sb.append("    siteLogo: ").append(toIndentedString(siteLogo)).append("\n");
    sb.append("    siteIcon: ").append(toIndentedString(siteIcon)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("title");
    openapiFields.add("description");
    openapiFields.add("url");
    openapiFields.add("email");
    openapiFields.add("timezone");
    openapiFields.add("date_format");
    openapiFields.add("time_format");
    openapiFields.add("start_of_week");
    openapiFields.add("language");
    openapiFields.add("use_smilies");
    openapiFields.add("default_category");
    openapiFields.add("default_post_format");
    openapiFields.add("posts_per_page");
    openapiFields.add("show_on_front");
    openapiFields.add("page_on_front");
    openapiFields.add("page_for_posts");
    openapiFields.add("default_ping_status");
    openapiFields.add("default_comment_status");
    openapiFields.add("site_logo");
    openapiFields.add("site_icon");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Settings
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Settings.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Settings is not found in the empty JSON string", Settings.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Settings.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `Settings` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("title") != null && !jsonObj.get("title").isJsonNull()) && !jsonObj.get("title").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `title` to be a primitive type in the JSON string but got `%s`", jsonObj.get("title").toString()));
      }
      if ((jsonObj.get("description") != null && !jsonObj.get("description").isJsonNull()) && !jsonObj.get("description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description").toString()));
      }
      if ((jsonObj.get("url") != null && !jsonObj.get("url").isJsonNull()) && !jsonObj.get("url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("url").toString()));
      }
      if ((jsonObj.get("email") != null && !jsonObj.get("email").isJsonNull()) && !jsonObj.get("email").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `email` to be a primitive type in the JSON string but got `%s`", jsonObj.get("email").toString()));
      }
      if ((jsonObj.get("timezone") != null && !jsonObj.get("timezone").isJsonNull()) && !jsonObj.get("timezone").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `timezone` to be a primitive type in the JSON string but got `%s`", jsonObj.get("timezone").toString()));
      }
      if ((jsonObj.get("date_format") != null && !jsonObj.get("date_format").isJsonNull()) && !jsonObj.get("date_format").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `date_format` to be a primitive type in the JSON string but got `%s`", jsonObj.get("date_format").toString()));
      }
      if ((jsonObj.get("time_format") != null && !jsonObj.get("time_format").isJsonNull()) && !jsonObj.get("time_format").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `time_format` to be a primitive type in the JSON string but got `%s`", jsonObj.get("time_format").toString()));
      }
      if ((jsonObj.get("language") != null && !jsonObj.get("language").isJsonNull()) && !jsonObj.get("language").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `language` to be a primitive type in the JSON string but got `%s`", jsonObj.get("language").toString()));
      }
      if ((jsonObj.get("default_post_format") != null && !jsonObj.get("default_post_format").isJsonNull()) && !jsonObj.get("default_post_format").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `default_post_format` to be a primitive type in the JSON string but got `%s`", jsonObj.get("default_post_format").toString()));
      }
      if ((jsonObj.get("show_on_front") != null && !jsonObj.get("show_on_front").isJsonNull()) && !jsonObj.get("show_on_front").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `show_on_front` to be a primitive type in the JSON string but got `%s`", jsonObj.get("show_on_front").toString()));
      }
      if ((jsonObj.get("default_ping_status") != null && !jsonObj.get("default_ping_status").isJsonNull()) && !jsonObj.get("default_ping_status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `default_ping_status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("default_ping_status").toString()));
      }
      // validate the optional field `default_ping_status`
      if (jsonObj.get("default_ping_status") != null && !jsonObj.get("default_ping_status").isJsonNull()) {
        DefaultPingStatusEnum.validateJsonElement(jsonObj.get("default_ping_status"));
      }
      if ((jsonObj.get("default_comment_status") != null && !jsonObj.get("default_comment_status").isJsonNull()) && !jsonObj.get("default_comment_status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `default_comment_status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("default_comment_status").toString()));
      }
      // validate the optional field `default_comment_status`
      if (jsonObj.get("default_comment_status") != null && !jsonObj.get("default_comment_status").isJsonNull()) {
        DefaultCommentStatusEnum.validateJsonElement(jsonObj.get("default_comment_status"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Settings.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Settings' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Settings> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Settings.class));

       return (TypeAdapter<T>) new TypeAdapter<Settings>() {
           @Override
           public void write(JsonWriter out, Settings value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Settings read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Settings given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Settings
   * @throws IOException if the JSON string is invalid with respect to Settings
   */
  public static Settings fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Settings.class);
  }

  /**
   * Convert an instance of Settings to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

