/*
 * WordPress REST API
 * The WordPress REST API is a powerful part of WordPress that lets you read and write various parts of WordPress data such as posts, pages, users, media, categories, tags, and custom content types defined in the installation.
 *
 * The version of the OpenAPI document: v2
 * Contact: labs@wtx.pl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pl.wtx.wordpress.api.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import pl.wtx.wordpress.api.client.invoker.JSON;

/**
 * Tags indicating styles and features of the theme.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class ThemeTags {
  public static final String SERIALIZED_NAME_RAW = "raw";
  @SerializedName(SERIALIZED_NAME_RAW)
  @javax.annotation.Nullable
  private List<String> raw = new ArrayList<>();

  public static final String SERIALIZED_NAME_RENDERED = "rendered";
  @SerializedName(SERIALIZED_NAME_RENDERED)
  @javax.annotation.Nullable
  private String rendered;

  public ThemeTags() {
  }

  public ThemeTags raw(@javax.annotation.Nullable List<String> raw) {
    this.raw = raw;
    return this;
  }

  public ThemeTags addRawItem(String rawItem) {
    if (this.raw == null) {
      this.raw = new ArrayList<>();
    }
    this.raw.add(rawItem);
    return this;
  }

  /**
   * The theme tags, as found in the theme header.
   * @return raw
   */
  @javax.annotation.Nullable
  public List<String> getRaw() {
    return raw;
  }

  public void setRaw(@javax.annotation.Nullable List<String> raw) {
    this.raw = raw;
  }


  public ThemeTags rendered(@javax.annotation.Nullable String rendered) {
    this.rendered = rendered;
    return this;
  }

  /**
   * The theme tags, transformed for display.
   * @return rendered
   */
  @javax.annotation.Nullable
  public String getRendered() {
    return rendered;
  }

  public void setRendered(@javax.annotation.Nullable String rendered) {
    this.rendered = rendered;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ThemeTags themeTags = (ThemeTags) o;
    return Objects.equals(this.raw, themeTags.raw) &&
        Objects.equals(this.rendered, themeTags.rendered);
  }

  @Override
  public int hashCode() {
    return Objects.hash(raw, rendered);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ThemeTags {\n");
    sb.append("    raw: ").append(toIndentedString(raw)).append("\n");
    sb.append("    rendered: ").append(toIndentedString(rendered)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("raw");
    openapiFields.add("rendered");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ThemeTags
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ThemeTags.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ThemeTags is not found in the empty JSON string", ThemeTags.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ThemeTags.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ThemeTags` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the optional json data is an array if present
      if (jsonObj.get("raw") != null && !jsonObj.get("raw").isJsonNull() && !jsonObj.get("raw").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `raw` to be an array in the JSON string but got `%s`", jsonObj.get("raw").toString()));
      }
      if ((jsonObj.get("rendered") != null && !jsonObj.get("rendered").isJsonNull()) && !jsonObj.get("rendered").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `rendered` to be a primitive type in the JSON string but got `%s`", jsonObj.get("rendered").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ThemeTags.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ThemeTags' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ThemeTags> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ThemeTags.class));

       return (TypeAdapter<T>) new TypeAdapter<ThemeTags>() {
           @Override
           public void write(JsonWriter out, ThemeTags value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ThemeTags read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ThemeTags given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ThemeTags
   * @throws IOException if the JSON string is invalid with respect to ThemeTags
   */
  public static ThemeTags fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ThemeTags.class);
  }

  /**
   * Convert an instance of ThemeTags to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

