/*
 * WordPress REST API
 * The WordPress REST API is a powerful part of WordPress that lets you read and write various parts of WordPress data such as posts, pages, users, media, categories, tags, and custom content types defined in the installation.
 *
 * The version of the OpenAPI document: v2
 * Contact: labs@wtx.pl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pl.wtx.wordpress.api.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.net.URI;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import pl.wtx.wordpress.api.client.model.ThemeAuthor;
import pl.wtx.wordpress.api.client.model.ThemeAuthorUri;
import pl.wtx.wordpress.api.client.model.ThemeDefaultTemplatePartAreasInner;
import pl.wtx.wordpress.api.client.model.ThemeDefaultTemplateTypesInner;
import pl.wtx.wordpress.api.client.model.ThemeDescription;
import pl.wtx.wordpress.api.client.model.ThemeName;
import pl.wtx.wordpress.api.client.model.ThemeTags;
import pl.wtx.wordpress.api.client.model.ThemeThemeSupports;
import pl.wtx.wordpress.api.client.model.ThemeThemeUri;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import pl.wtx.wordpress.api.client.invoker.JSON;

/**
 * Theme
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class Theme {
  public static final String SERIALIZED_NAME_STYLESHEET = "stylesheet";
  @SerializedName(SERIALIZED_NAME_STYLESHEET)
  @javax.annotation.Nullable
  private String stylesheet;

  public static final String SERIALIZED_NAME_STYLESHEET_URI = "stylesheet_uri";
  @SerializedName(SERIALIZED_NAME_STYLESHEET_URI)
  @javax.annotation.Nullable
  private URI stylesheetUri;

  public static final String SERIALIZED_NAME_TEMPLATE = "template";
  @SerializedName(SERIALIZED_NAME_TEMPLATE)
  @javax.annotation.Nullable
  private String template;

  public static final String SERIALIZED_NAME_TEMPLATE_URI = "template_uri";
  @SerializedName(SERIALIZED_NAME_TEMPLATE_URI)
  @javax.annotation.Nullable
  private URI templateUri;

  public static final String SERIALIZED_NAME_AUTHOR = "author";
  @SerializedName(SERIALIZED_NAME_AUTHOR)
  @javax.annotation.Nullable
  private ThemeAuthor author;

  public static final String SERIALIZED_NAME_AUTHOR_URI = "author_uri";
  @SerializedName(SERIALIZED_NAME_AUTHOR_URI)
  @javax.annotation.Nullable
  private ThemeAuthorUri authorUri;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  @javax.annotation.Nullable
  private ThemeDescription description;

  public static final String SERIALIZED_NAME_IS_BLOCK_THEME = "is_block_theme";
  @SerializedName(SERIALIZED_NAME_IS_BLOCK_THEME)
  @javax.annotation.Nullable
  private Boolean isBlockTheme;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nullable
  private ThemeName name;

  public static final String SERIALIZED_NAME_REQUIRES_PHP = "requires_php";
  @SerializedName(SERIALIZED_NAME_REQUIRES_PHP)
  @javax.annotation.Nullable
  private String requiresPhp;

  public static final String SERIALIZED_NAME_REQUIRES_WP = "requires_wp";
  @SerializedName(SERIALIZED_NAME_REQUIRES_WP)
  @javax.annotation.Nullable
  private String requiresWp;

  public static final String SERIALIZED_NAME_SCREENSHOT = "screenshot";
  @SerializedName(SERIALIZED_NAME_SCREENSHOT)
  @javax.annotation.Nullable
  private URI screenshot;

  public static final String SERIALIZED_NAME_TAGS = "tags";
  @SerializedName(SERIALIZED_NAME_TAGS)
  @javax.annotation.Nullable
  private ThemeTags tags;

  public static final String SERIALIZED_NAME_TEXTDOMAIN = "textdomain";
  @SerializedName(SERIALIZED_NAME_TEXTDOMAIN)
  @javax.annotation.Nullable
  private String textdomain;

  public static final String SERIALIZED_NAME_THEME_SUPPORTS = "theme_supports";
  @SerializedName(SERIALIZED_NAME_THEME_SUPPORTS)
  @javax.annotation.Nullable
  private ThemeThemeSupports themeSupports;

  public static final String SERIALIZED_NAME_THEME_URI = "theme_uri";
  @SerializedName(SERIALIZED_NAME_THEME_URI)
  @javax.annotation.Nullable
  private ThemeThemeUri themeUri;

  public static final String SERIALIZED_NAME_VERSION = "version";
  @SerializedName(SERIALIZED_NAME_VERSION)
  @javax.annotation.Nullable
  private String version;

  /**
   * A named status for the theme.
   */
  @JsonAdapter(StatusEnum.Adapter.class)
  public enum StatusEnum {
    INACTIVE("inactive"),
    
    ACTIVE("active");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return StatusEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      StatusEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nullable
  private StatusEnum status;

  public static final String SERIALIZED_NAME_DEFAULT_TEMPLATE_TYPES = "default_template_types";
  @SerializedName(SERIALIZED_NAME_DEFAULT_TEMPLATE_TYPES)
  @javax.annotation.Nullable
  private List<ThemeDefaultTemplateTypesInner> defaultTemplateTypes = new ArrayList<>();

  public static final String SERIALIZED_NAME_DEFAULT_TEMPLATE_PART_AREAS = "default_template_part_areas";
  @SerializedName(SERIALIZED_NAME_DEFAULT_TEMPLATE_PART_AREAS)
  @javax.annotation.Nullable
  private List<ThemeDefaultTemplatePartAreasInner> defaultTemplatePartAreas = new ArrayList<>();

  public Theme() {
  }

  public Theme stylesheet(@javax.annotation.Nullable String stylesheet) {
    this.stylesheet = stylesheet;
    return this;
  }

  /**
   * The theme&#39;s stylesheet. This uniquely identifies the theme.
   * @return stylesheet
   */
  @javax.annotation.Nullable
  public String getStylesheet() {
    return stylesheet;
  }

  public void setStylesheet(@javax.annotation.Nullable String stylesheet) {
    this.stylesheet = stylesheet;
  }


  public Theme stylesheetUri(@javax.annotation.Nullable URI stylesheetUri) {
    this.stylesheetUri = stylesheetUri;
    return this;
  }

  /**
   * The uri for the theme&#39;s stylesheet directory.
   * @return stylesheetUri
   */
  @javax.annotation.Nullable
  public URI getStylesheetUri() {
    return stylesheetUri;
  }

  public void setStylesheetUri(@javax.annotation.Nullable URI stylesheetUri) {
    this.stylesheetUri = stylesheetUri;
  }


  public Theme template(@javax.annotation.Nullable String template) {
    this.template = template;
    return this;
  }

  /**
   * The theme&#39;s template. If this is a child theme, this refers to the parent theme, otherwise this is the same as the theme&#39;s stylesheet.
   * @return template
   */
  @javax.annotation.Nullable
  public String getTemplate() {
    return template;
  }

  public void setTemplate(@javax.annotation.Nullable String template) {
    this.template = template;
  }


  public Theme templateUri(@javax.annotation.Nullable URI templateUri) {
    this.templateUri = templateUri;
    return this;
  }

  /**
   * The uri for the theme&#39;s template directory. If this is a child theme, this refers to the parent theme, otherwise this is the same as the theme&#39;s stylesheet directory.
   * @return templateUri
   */
  @javax.annotation.Nullable
  public URI getTemplateUri() {
    return templateUri;
  }

  public void setTemplateUri(@javax.annotation.Nullable URI templateUri) {
    this.templateUri = templateUri;
  }


  public Theme author(@javax.annotation.Nullable ThemeAuthor author) {
    this.author = author;
    return this;
  }

  /**
   * Get author
   * @return author
   */
  @javax.annotation.Nullable
  public ThemeAuthor getAuthor() {
    return author;
  }

  public void setAuthor(@javax.annotation.Nullable ThemeAuthor author) {
    this.author = author;
  }


  public Theme authorUri(@javax.annotation.Nullable ThemeAuthorUri authorUri) {
    this.authorUri = authorUri;
    return this;
  }

  /**
   * Get authorUri
   * @return authorUri
   */
  @javax.annotation.Nullable
  public ThemeAuthorUri getAuthorUri() {
    return authorUri;
  }

  public void setAuthorUri(@javax.annotation.Nullable ThemeAuthorUri authorUri) {
    this.authorUri = authorUri;
  }


  public Theme description(@javax.annotation.Nullable ThemeDescription description) {
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @javax.annotation.Nullable
  public ThemeDescription getDescription() {
    return description;
  }

  public void setDescription(@javax.annotation.Nullable ThemeDescription description) {
    this.description = description;
  }


  public Theme isBlockTheme(@javax.annotation.Nullable Boolean isBlockTheme) {
    this.isBlockTheme = isBlockTheme;
    return this;
  }

  /**
   * Whether the theme is a block-based theme.
   * @return isBlockTheme
   */
  @javax.annotation.Nullable
  public Boolean getIsBlockTheme() {
    return isBlockTheme;
  }

  public void setIsBlockTheme(@javax.annotation.Nullable Boolean isBlockTheme) {
    this.isBlockTheme = isBlockTheme;
  }


  public Theme name(@javax.annotation.Nullable ThemeName name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nullable
  public ThemeName getName() {
    return name;
  }

  public void setName(@javax.annotation.Nullable ThemeName name) {
    this.name = name;
  }


  public Theme requiresPhp(@javax.annotation.Nullable String requiresPhp) {
    this.requiresPhp = requiresPhp;
    return this;
  }

  /**
   * The minimum PHP version required for the theme to work.
   * @return requiresPhp
   */
  @javax.annotation.Nullable
  public String getRequiresPhp() {
    return requiresPhp;
  }

  public void setRequiresPhp(@javax.annotation.Nullable String requiresPhp) {
    this.requiresPhp = requiresPhp;
  }


  public Theme requiresWp(@javax.annotation.Nullable String requiresWp) {
    this.requiresWp = requiresWp;
    return this;
  }

  /**
   * The minimum WordPress version required for the theme to work.
   * @return requiresWp
   */
  @javax.annotation.Nullable
  public String getRequiresWp() {
    return requiresWp;
  }

  public void setRequiresWp(@javax.annotation.Nullable String requiresWp) {
    this.requiresWp = requiresWp;
  }


  public Theme screenshot(@javax.annotation.Nullable URI screenshot) {
    this.screenshot = screenshot;
    return this;
  }

  /**
   * The theme&#39;s screenshot URL.
   * @return screenshot
   */
  @javax.annotation.Nullable
  public URI getScreenshot() {
    return screenshot;
  }

  public void setScreenshot(@javax.annotation.Nullable URI screenshot) {
    this.screenshot = screenshot;
  }


  public Theme tags(@javax.annotation.Nullable ThemeTags tags) {
    this.tags = tags;
    return this;
  }

  /**
   * Get tags
   * @return tags
   */
  @javax.annotation.Nullable
  public ThemeTags getTags() {
    return tags;
  }

  public void setTags(@javax.annotation.Nullable ThemeTags tags) {
    this.tags = tags;
  }


  public Theme textdomain(@javax.annotation.Nullable String textdomain) {
    this.textdomain = textdomain;
    return this;
  }

  /**
   * The theme&#39;s text domain.
   * @return textdomain
   */
  @javax.annotation.Nullable
  public String getTextdomain() {
    return textdomain;
  }

  public void setTextdomain(@javax.annotation.Nullable String textdomain) {
    this.textdomain = textdomain;
  }


  public Theme themeSupports(@javax.annotation.Nullable ThemeThemeSupports themeSupports) {
    this.themeSupports = themeSupports;
    return this;
  }

  /**
   * Get themeSupports
   * @return themeSupports
   */
  @javax.annotation.Nullable
  public ThemeThemeSupports getThemeSupports() {
    return themeSupports;
  }

  public void setThemeSupports(@javax.annotation.Nullable ThemeThemeSupports themeSupports) {
    this.themeSupports = themeSupports;
  }


  public Theme themeUri(@javax.annotation.Nullable ThemeThemeUri themeUri) {
    this.themeUri = themeUri;
    return this;
  }

  /**
   * Get themeUri
   * @return themeUri
   */
  @javax.annotation.Nullable
  public ThemeThemeUri getThemeUri() {
    return themeUri;
  }

  public void setThemeUri(@javax.annotation.Nullable ThemeThemeUri themeUri) {
    this.themeUri = themeUri;
  }


  public Theme version(@javax.annotation.Nullable String version) {
    this.version = version;
    return this;
  }

  /**
   * The theme&#39;s current version.
   * @return version
   */
  @javax.annotation.Nullable
  public String getVersion() {
    return version;
  }

  public void setVersion(@javax.annotation.Nullable String version) {
    this.version = version;
  }


  public Theme status(@javax.annotation.Nullable StatusEnum status) {
    this.status = status;
    return this;
  }

  /**
   * A named status for the theme.
   * @return status
   */
  @javax.annotation.Nullable
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nullable StatusEnum status) {
    this.status = status;
  }


  public Theme defaultTemplateTypes(@javax.annotation.Nullable List<ThemeDefaultTemplateTypesInner> defaultTemplateTypes) {
    this.defaultTemplateTypes = defaultTemplateTypes;
    return this;
  }

  public Theme addDefaultTemplateTypesItem(ThemeDefaultTemplateTypesInner defaultTemplateTypesItem) {
    if (this.defaultTemplateTypes == null) {
      this.defaultTemplateTypes = new ArrayList<>();
    }
    this.defaultTemplateTypes.add(defaultTemplateTypesItem);
    return this;
  }

  /**
   * A list of default template types.
   * @return defaultTemplateTypes
   */
  @javax.annotation.Nullable
  public List<ThemeDefaultTemplateTypesInner> getDefaultTemplateTypes() {
    return defaultTemplateTypes;
  }

  public void setDefaultTemplateTypes(@javax.annotation.Nullable List<ThemeDefaultTemplateTypesInner> defaultTemplateTypes) {
    this.defaultTemplateTypes = defaultTemplateTypes;
  }


  public Theme defaultTemplatePartAreas(@javax.annotation.Nullable List<ThemeDefaultTemplatePartAreasInner> defaultTemplatePartAreas) {
    this.defaultTemplatePartAreas = defaultTemplatePartAreas;
    return this;
  }

  public Theme addDefaultTemplatePartAreasItem(ThemeDefaultTemplatePartAreasInner defaultTemplatePartAreasItem) {
    if (this.defaultTemplatePartAreas == null) {
      this.defaultTemplatePartAreas = new ArrayList<>();
    }
    this.defaultTemplatePartAreas.add(defaultTemplatePartAreasItem);
    return this;
  }

  /**
   * A list of allowed area values for template parts.
   * @return defaultTemplatePartAreas
   */
  @javax.annotation.Nullable
  public List<ThemeDefaultTemplatePartAreasInner> getDefaultTemplatePartAreas() {
    return defaultTemplatePartAreas;
  }

  public void setDefaultTemplatePartAreas(@javax.annotation.Nullable List<ThemeDefaultTemplatePartAreasInner> defaultTemplatePartAreas) {
    this.defaultTemplatePartAreas = defaultTemplatePartAreas;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Theme theme = (Theme) o;
    return Objects.equals(this.stylesheet, theme.stylesheet) &&
        Objects.equals(this.stylesheetUri, theme.stylesheetUri) &&
        Objects.equals(this.template, theme.template) &&
        Objects.equals(this.templateUri, theme.templateUri) &&
        Objects.equals(this.author, theme.author) &&
        Objects.equals(this.authorUri, theme.authorUri) &&
        Objects.equals(this.description, theme.description) &&
        Objects.equals(this.isBlockTheme, theme.isBlockTheme) &&
        Objects.equals(this.name, theme.name) &&
        Objects.equals(this.requiresPhp, theme.requiresPhp) &&
        Objects.equals(this.requiresWp, theme.requiresWp) &&
        Objects.equals(this.screenshot, theme.screenshot) &&
        Objects.equals(this.tags, theme.tags) &&
        Objects.equals(this.textdomain, theme.textdomain) &&
        Objects.equals(this.themeSupports, theme.themeSupports) &&
        Objects.equals(this.themeUri, theme.themeUri) &&
        Objects.equals(this.version, theme.version) &&
        Objects.equals(this.status, theme.status) &&
        Objects.equals(this.defaultTemplateTypes, theme.defaultTemplateTypes) &&
        Objects.equals(this.defaultTemplatePartAreas, theme.defaultTemplatePartAreas);
  }

  @Override
  public int hashCode() {
    return Objects.hash(stylesheet, stylesheetUri, template, templateUri, author, authorUri, description, isBlockTheme, name, requiresPhp, requiresWp, screenshot, tags, textdomain, themeSupports, themeUri, version, status, defaultTemplateTypes, defaultTemplatePartAreas);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Theme {\n");
    sb.append("    stylesheet: ").append(toIndentedString(stylesheet)).append("\n");
    sb.append("    stylesheetUri: ").append(toIndentedString(stylesheetUri)).append("\n");
    sb.append("    template: ").append(toIndentedString(template)).append("\n");
    sb.append("    templateUri: ").append(toIndentedString(templateUri)).append("\n");
    sb.append("    author: ").append(toIndentedString(author)).append("\n");
    sb.append("    authorUri: ").append(toIndentedString(authorUri)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    isBlockTheme: ").append(toIndentedString(isBlockTheme)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    requiresPhp: ").append(toIndentedString(requiresPhp)).append("\n");
    sb.append("    requiresWp: ").append(toIndentedString(requiresWp)).append("\n");
    sb.append("    screenshot: ").append(toIndentedString(screenshot)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    textdomain: ").append(toIndentedString(textdomain)).append("\n");
    sb.append("    themeSupports: ").append(toIndentedString(themeSupports)).append("\n");
    sb.append("    themeUri: ").append(toIndentedString(themeUri)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    defaultTemplateTypes: ").append(toIndentedString(defaultTemplateTypes)).append("\n");
    sb.append("    defaultTemplatePartAreas: ").append(toIndentedString(defaultTemplatePartAreas)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("stylesheet");
    openapiFields.add("stylesheet_uri");
    openapiFields.add("template");
    openapiFields.add("template_uri");
    openapiFields.add("author");
    openapiFields.add("author_uri");
    openapiFields.add("description");
    openapiFields.add("is_block_theme");
    openapiFields.add("name");
    openapiFields.add("requires_php");
    openapiFields.add("requires_wp");
    openapiFields.add("screenshot");
    openapiFields.add("tags");
    openapiFields.add("textdomain");
    openapiFields.add("theme_supports");
    openapiFields.add("theme_uri");
    openapiFields.add("version");
    openapiFields.add("status");
    openapiFields.add("default_template_types");
    openapiFields.add("default_template_part_areas");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Theme
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Theme.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Theme is not found in the empty JSON string", Theme.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Theme.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `Theme` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("stylesheet") != null && !jsonObj.get("stylesheet").isJsonNull()) && !jsonObj.get("stylesheet").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `stylesheet` to be a primitive type in the JSON string but got `%s`", jsonObj.get("stylesheet").toString()));
      }
      if ((jsonObj.get("stylesheet_uri") != null && !jsonObj.get("stylesheet_uri").isJsonNull()) && !jsonObj.get("stylesheet_uri").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `stylesheet_uri` to be a primitive type in the JSON string but got `%s`", jsonObj.get("stylesheet_uri").toString()));
      }
      if ((jsonObj.get("template") != null && !jsonObj.get("template").isJsonNull()) && !jsonObj.get("template").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `template` to be a primitive type in the JSON string but got `%s`", jsonObj.get("template").toString()));
      }
      if ((jsonObj.get("template_uri") != null && !jsonObj.get("template_uri").isJsonNull()) && !jsonObj.get("template_uri").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `template_uri` to be a primitive type in the JSON string but got `%s`", jsonObj.get("template_uri").toString()));
      }
      // validate the optional field `author`
      if (jsonObj.get("author") != null && !jsonObj.get("author").isJsonNull()) {
        ThemeAuthor.validateJsonElement(jsonObj.get("author"));
      }
      // validate the optional field `author_uri`
      if (jsonObj.get("author_uri") != null && !jsonObj.get("author_uri").isJsonNull()) {
        ThemeAuthorUri.validateJsonElement(jsonObj.get("author_uri"));
      }
      // validate the optional field `description`
      if (jsonObj.get("description") != null && !jsonObj.get("description").isJsonNull()) {
        ThemeDescription.validateJsonElement(jsonObj.get("description"));
      }
      // validate the optional field `name`
      if (jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) {
        ThemeName.validateJsonElement(jsonObj.get("name"));
      }
      if ((jsonObj.get("requires_php") != null && !jsonObj.get("requires_php").isJsonNull()) && !jsonObj.get("requires_php").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `requires_php` to be a primitive type in the JSON string but got `%s`", jsonObj.get("requires_php").toString()));
      }
      if ((jsonObj.get("requires_wp") != null && !jsonObj.get("requires_wp").isJsonNull()) && !jsonObj.get("requires_wp").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `requires_wp` to be a primitive type in the JSON string but got `%s`", jsonObj.get("requires_wp").toString()));
      }
      if ((jsonObj.get("screenshot") != null && !jsonObj.get("screenshot").isJsonNull()) && !jsonObj.get("screenshot").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `screenshot` to be a primitive type in the JSON string but got `%s`", jsonObj.get("screenshot").toString()));
      }
      // validate the optional field `tags`
      if (jsonObj.get("tags") != null && !jsonObj.get("tags").isJsonNull()) {
        ThemeTags.validateJsonElement(jsonObj.get("tags"));
      }
      if ((jsonObj.get("textdomain") != null && !jsonObj.get("textdomain").isJsonNull()) && !jsonObj.get("textdomain").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `textdomain` to be a primitive type in the JSON string but got `%s`", jsonObj.get("textdomain").toString()));
      }
      // validate the optional field `theme_supports`
      if (jsonObj.get("theme_supports") != null && !jsonObj.get("theme_supports").isJsonNull()) {
        ThemeThemeSupports.validateJsonElement(jsonObj.get("theme_supports"));
      }
      // validate the optional field `theme_uri`
      if (jsonObj.get("theme_uri") != null && !jsonObj.get("theme_uri").isJsonNull()) {
        ThemeThemeUri.validateJsonElement(jsonObj.get("theme_uri"));
      }
      if ((jsonObj.get("version") != null && !jsonObj.get("version").isJsonNull()) && !jsonObj.get("version").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `version` to be a primitive type in the JSON string but got `%s`", jsonObj.get("version").toString()));
      }
      if ((jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) && !jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
      // validate the optional field `status`
      if (jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) {
        StatusEnum.validateJsonElement(jsonObj.get("status"));
      }
      if (jsonObj.get("default_template_types") != null && !jsonObj.get("default_template_types").isJsonNull()) {
        JsonArray jsonArraydefaultTemplateTypes = jsonObj.getAsJsonArray("default_template_types");
        if (jsonArraydefaultTemplateTypes != null) {
          // ensure the json data is an array
          if (!jsonObj.get("default_template_types").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `default_template_types` to be an array in the JSON string but got `%s`", jsonObj.get("default_template_types").toString()));
          }

          // validate the optional field `default_template_types` (array)
          for (int i = 0; i < jsonArraydefaultTemplateTypes.size(); i++) {
            ThemeDefaultTemplateTypesInner.validateJsonElement(jsonArraydefaultTemplateTypes.get(i));
          };
        }
      }
      if (jsonObj.get("default_template_part_areas") != null && !jsonObj.get("default_template_part_areas").isJsonNull()) {
        JsonArray jsonArraydefaultTemplatePartAreas = jsonObj.getAsJsonArray("default_template_part_areas");
        if (jsonArraydefaultTemplatePartAreas != null) {
          // ensure the json data is an array
          if (!jsonObj.get("default_template_part_areas").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `default_template_part_areas` to be an array in the JSON string but got `%s`", jsonObj.get("default_template_part_areas").toString()));
          }

          // validate the optional field `default_template_part_areas` (array)
          for (int i = 0; i < jsonArraydefaultTemplatePartAreas.size(); i++) {
            ThemeDefaultTemplatePartAreasInner.validateJsonElement(jsonArraydefaultTemplatePartAreas.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Theme.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Theme' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Theme> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Theme.class));

       return (TypeAdapter<T>) new TypeAdapter<Theme>() {
           @Override
           public void write(JsonWriter out, Theme value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Theme read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Theme given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Theme
   * @throws IOException if the JSON string is invalid with respect to Theme
   */
  public static Theme fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Theme.class);
  }

  /**
   * Convert an instance of Theme to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

