/*
 * WordPress REST API
 * The WordPress REST API is a powerful part of WordPress that lets you read and write various parts of WordPress data such as posts, pages, users, media, categories, tags, and custom content types defined in the installation.
 *
 * The version of the OpenAPI document: v2
 * Contact: labs@wtx.pl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pl.wtx.wordpress.api.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import pl.wtx.wordpress.api.client.invoker.JSON;

/**
 * ThemeThemeSupportsEditorGradientPresetsOneOfInner
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class ThemeThemeSupportsEditorGradientPresetsOneOfInner {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nullable
  private String name;

  public static final String SERIALIZED_NAME_GRADIENT = "gradient";
  @SerializedName(SERIALIZED_NAME_GRADIENT)
  @javax.annotation.Nullable
  private String gradient;

  public static final String SERIALIZED_NAME_SLUG = "slug";
  @SerializedName(SERIALIZED_NAME_SLUG)
  @javax.annotation.Nullable
  private String slug;

  public ThemeThemeSupportsEditorGradientPresetsOneOfInner() {
  }

  public ThemeThemeSupportsEditorGradientPresetsOneOfInner name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public ThemeThemeSupportsEditorGradientPresetsOneOfInner gradient(@javax.annotation.Nullable String gradient) {
    this.gradient = gradient;
    return this;
  }

  /**
   * Get gradient
   * @return gradient
   */
  @javax.annotation.Nullable
  public String getGradient() {
    return gradient;
  }

  public void setGradient(@javax.annotation.Nullable String gradient) {
    this.gradient = gradient;
  }


  public ThemeThemeSupportsEditorGradientPresetsOneOfInner slug(@javax.annotation.Nullable String slug) {
    this.slug = slug;
    return this;
  }

  /**
   * Get slug
   * @return slug
   */
  @javax.annotation.Nullable
  public String getSlug() {
    return slug;
  }

  public void setSlug(@javax.annotation.Nullable String slug) {
    this.slug = slug;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ThemeThemeSupportsEditorGradientPresetsOneOfInner themeThemeSupportsEditorGradientPresetsOneOfInner = (ThemeThemeSupportsEditorGradientPresetsOneOfInner) o;
    return Objects.equals(this.name, themeThemeSupportsEditorGradientPresetsOneOfInner.name) &&
        Objects.equals(this.gradient, themeThemeSupportsEditorGradientPresetsOneOfInner.gradient) &&
        Objects.equals(this.slug, themeThemeSupportsEditorGradientPresetsOneOfInner.slug);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, gradient, slug);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ThemeThemeSupportsEditorGradientPresetsOneOfInner {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    gradient: ").append(toIndentedString(gradient)).append("\n");
    sb.append("    slug: ").append(toIndentedString(slug)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("name");
    openapiFields.add("gradient");
    openapiFields.add("slug");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ThemeThemeSupportsEditorGradientPresetsOneOfInner
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ThemeThemeSupportsEditorGradientPresetsOneOfInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ThemeThemeSupportsEditorGradientPresetsOneOfInner is not found in the empty JSON string", ThemeThemeSupportsEditorGradientPresetsOneOfInner.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ThemeThemeSupportsEditorGradientPresetsOneOfInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ThemeThemeSupportsEditorGradientPresetsOneOfInner` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("gradient") != null && !jsonObj.get("gradient").isJsonNull()) && !jsonObj.get("gradient").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `gradient` to be a primitive type in the JSON string but got `%s`", jsonObj.get("gradient").toString()));
      }
      if ((jsonObj.get("slug") != null && !jsonObj.get("slug").isJsonNull()) && !jsonObj.get("slug").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `slug` to be a primitive type in the JSON string but got `%s`", jsonObj.get("slug").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ThemeThemeSupportsEditorGradientPresetsOneOfInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ThemeThemeSupportsEditorGradientPresetsOneOfInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ThemeThemeSupportsEditorGradientPresetsOneOfInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ThemeThemeSupportsEditorGradientPresetsOneOfInner.class));

       return (TypeAdapter<T>) new TypeAdapter<ThemeThemeSupportsEditorGradientPresetsOneOfInner>() {
           @Override
           public void write(JsonWriter out, ThemeThemeSupportsEditorGradientPresetsOneOfInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ThemeThemeSupportsEditorGradientPresetsOneOfInner read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ThemeThemeSupportsEditorGradientPresetsOneOfInner given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ThemeThemeSupportsEditorGradientPresetsOneOfInner
   * @throws IOException if the JSON string is invalid with respect to ThemeThemeSupportsEditorGradientPresetsOneOfInner
   */
  public static ThemeThemeSupportsEditorGradientPresetsOneOfInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ThemeThemeSupportsEditorGradientPresetsOneOfInner.class);
  }

  /**
   * Convert an instance of ThemeThemeSupportsEditorGradientPresetsOneOfInner to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

