/*
 * WordPress REST API
 * The WordPress REST API is a powerful part of WordPress that lets you read and write various parts of WordPress data such as posts, pages, users, media, categories, tags, and custom content types defined in the installation.
 *
 * The version of the OpenAPI document: v2
 * Contact: labs@wtx.pl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pl.wtx.wordpress.api.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.net.URI;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import pl.wtx.wordpress.api.client.invoker.JSON;

/**
 * Avatar URLs for the user.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class UserAvatarUrls {
  public static final String SERIALIZED_NAME_24 = "24";
  @SerializedName(SERIALIZED_NAME_24)
  @javax.annotation.Nullable
  private URI _24;

  public static final String SERIALIZED_NAME_48 = "48";
  @SerializedName(SERIALIZED_NAME_48)
  @javax.annotation.Nullable
  private URI _48;

  public static final String SERIALIZED_NAME_96 = "96";
  @SerializedName(SERIALIZED_NAME_96)
  @javax.annotation.Nullable
  private URI _96;

  public UserAvatarUrls() {
  }

  public UserAvatarUrls _24(@javax.annotation.Nullable URI _24) {
    this._24 = _24;
    return this;
  }

  /**
   * Avatar URL with image size of 24 pixels.
   * @return _24
   */
  @javax.annotation.Nullable
  public URI get24() {
    return _24;
  }

  public void set24(@javax.annotation.Nullable URI _24) {
    this._24 = _24;
  }


  public UserAvatarUrls _48(@javax.annotation.Nullable URI _48) {
    this._48 = _48;
    return this;
  }

  /**
   * Avatar URL with image size of 48 pixels.
   * @return _48
   */
  @javax.annotation.Nullable
  public URI get48() {
    return _48;
  }

  public void set48(@javax.annotation.Nullable URI _48) {
    this._48 = _48;
  }


  public UserAvatarUrls _96(@javax.annotation.Nullable URI _96) {
    this._96 = _96;
    return this;
  }

  /**
   * Avatar URL with image size of 96 pixels.
   * @return _96
   */
  @javax.annotation.Nullable
  public URI get96() {
    return _96;
  }

  public void set96(@javax.annotation.Nullable URI _96) {
    this._96 = _96;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserAvatarUrls userAvatarUrls = (UserAvatarUrls) o;
    return Objects.equals(this._24, userAvatarUrls._24) &&
        Objects.equals(this._48, userAvatarUrls._48) &&
        Objects.equals(this._96, userAvatarUrls._96);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_24, _48, _96);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserAvatarUrls {\n");
    sb.append("    _24: ").append(toIndentedString(_24)).append("\n");
    sb.append("    _48: ").append(toIndentedString(_48)).append("\n");
    sb.append("    _96: ").append(toIndentedString(_96)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("24");
    openapiFields.add("48");
    openapiFields.add("96");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to UserAvatarUrls
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!UserAvatarUrls.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in UserAvatarUrls is not found in the empty JSON string", UserAvatarUrls.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!UserAvatarUrls.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `UserAvatarUrls` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("24") != null && !jsonObj.get("24").isJsonNull()) && !jsonObj.get("24").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `24` to be a primitive type in the JSON string but got `%s`", jsonObj.get("24").toString()));
      }
      if ((jsonObj.get("48") != null && !jsonObj.get("48").isJsonNull()) && !jsonObj.get("48").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `48` to be a primitive type in the JSON string but got `%s`", jsonObj.get("48").toString()));
      }
      if ((jsonObj.get("96") != null && !jsonObj.get("96").isJsonNull()) && !jsonObj.get("96").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `96` to be a primitive type in the JSON string but got `%s`", jsonObj.get("96").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!UserAvatarUrls.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'UserAvatarUrls' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<UserAvatarUrls> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(UserAvatarUrls.class));

       return (TypeAdapter<T>) new TypeAdapter<UserAvatarUrls>() {
           @Override
           public void write(JsonWriter out, UserAvatarUrls value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public UserAvatarUrls read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of UserAvatarUrls given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of UserAvatarUrls
   * @throws IOException if the JSON string is invalid with respect to UserAvatarUrls
   */
  public static UserAvatarUrls fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, UserAvatarUrls.class);
  }

  /**
   * Convert an instance of UserAvatarUrls to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

