/*
 * WordPress REST API
 * The WordPress REST API is a powerful part of WordPress that lets you read and write various parts of WordPress data such as posts, pages, users, media, categories, tags, and custom content types defined in the installation.
 *
 * The version of the OpenAPI document: v2
 * Contact: labs@wtx.pl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pl.wtx.wordpress.api.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import pl.wtx.wordpress.api.client.model.WidgetsPostRequestInstance;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import pl.wtx.wordpress.api.client.invoker.JSON;

/**
 * Widget
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class Widget {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private String id;

  public static final String SERIALIZED_NAME_ID_BASE = "id_base";
  @SerializedName(SERIALIZED_NAME_ID_BASE)
  @javax.annotation.Nullable
  private String idBase;

  public static final String SERIALIZED_NAME_SIDEBAR = "sidebar";
  @SerializedName(SERIALIZED_NAME_SIDEBAR)
  @javax.annotation.Nullable
  private String sidebar = "wp_inactive_widgets";

  public static final String SERIALIZED_NAME_RENDERED = "rendered";
  @SerializedName(SERIALIZED_NAME_RENDERED)
  @javax.annotation.Nullable
  private String rendered;

  public static final String SERIALIZED_NAME_RENDERED_FORM = "rendered_form";
  @SerializedName(SERIALIZED_NAME_RENDERED_FORM)
  @javax.annotation.Nullable
  private String renderedForm;

  public static final String SERIALIZED_NAME_INSTANCE = "instance";
  @SerializedName(SERIALIZED_NAME_INSTANCE)
  @javax.annotation.Nullable
  private WidgetsPostRequestInstance instance;

  public static final String SERIALIZED_NAME_FORM_DATA = "form_data";
  @SerializedName(SERIALIZED_NAME_FORM_DATA)
  @javax.annotation.Nullable
  private String formData;

  public Widget() {
  }

  public Widget id(@javax.annotation.Nullable String id) {
    this.id = id;
    return this;
  }

  /**
   * Unique identifier for the widget.
   * @return id
   */
  @javax.annotation.Nullable
  public String getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }


  public Widget idBase(@javax.annotation.Nullable String idBase) {
    this.idBase = idBase;
    return this;
  }

  /**
   * The type of the widget. Corresponds to ID in widget-types endpoint.
   * @return idBase
   */
  @javax.annotation.Nullable
  public String getIdBase() {
    return idBase;
  }

  public void setIdBase(@javax.annotation.Nullable String idBase) {
    this.idBase = idBase;
  }


  public Widget sidebar(@javax.annotation.Nullable String sidebar) {
    this.sidebar = sidebar;
    return this;
  }

  /**
   * The sidebar the widget belongs to.
   * @return sidebar
   */
  @javax.annotation.Nullable
  public String getSidebar() {
    return sidebar;
  }

  public void setSidebar(@javax.annotation.Nullable String sidebar) {
    this.sidebar = sidebar;
  }


  public Widget rendered(@javax.annotation.Nullable String rendered) {
    this.rendered = rendered;
    return this;
  }

  /**
   * HTML representation of the widget.
   * @return rendered
   */
  @javax.annotation.Nullable
  public String getRendered() {
    return rendered;
  }

  public void setRendered(@javax.annotation.Nullable String rendered) {
    this.rendered = rendered;
  }


  public Widget renderedForm(@javax.annotation.Nullable String renderedForm) {
    this.renderedForm = renderedForm;
    return this;
  }

  /**
   * HTML representation of the widget admin form.
   * @return renderedForm
   */
  @javax.annotation.Nullable
  public String getRenderedForm() {
    return renderedForm;
  }

  public void setRenderedForm(@javax.annotation.Nullable String renderedForm) {
    this.renderedForm = renderedForm;
  }


  public Widget instance(@javax.annotation.Nullable WidgetsPostRequestInstance instance) {
    this.instance = instance;
    return this;
  }

  /**
   * Get instance
   * @return instance
   */
  @javax.annotation.Nullable
  public WidgetsPostRequestInstance getInstance() {
    return instance;
  }

  public void setInstance(@javax.annotation.Nullable WidgetsPostRequestInstance instance) {
    this.instance = instance;
  }


  public Widget formData(@javax.annotation.Nullable String formData) {
    this.formData = formData;
    return this;
  }

  /**
   * URL-encoded form data from the widget admin form. Used to update a widget that does not support instance. Write only.
   * @return formData
   */
  @javax.annotation.Nullable
  public String getFormData() {
    return formData;
  }

  public void setFormData(@javax.annotation.Nullable String formData) {
    this.formData = formData;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Widget widget = (Widget) o;
    return Objects.equals(this.id, widget.id) &&
        Objects.equals(this.idBase, widget.idBase) &&
        Objects.equals(this.sidebar, widget.sidebar) &&
        Objects.equals(this.rendered, widget.rendered) &&
        Objects.equals(this.renderedForm, widget.renderedForm) &&
        Objects.equals(this.instance, widget.instance) &&
        Objects.equals(this.formData, widget.formData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, idBase, sidebar, rendered, renderedForm, instance, formData);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Widget {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    idBase: ").append(toIndentedString(idBase)).append("\n");
    sb.append("    sidebar: ").append(toIndentedString(sidebar)).append("\n");
    sb.append("    rendered: ").append(toIndentedString(rendered)).append("\n");
    sb.append("    renderedForm: ").append(toIndentedString(renderedForm)).append("\n");
    sb.append("    instance: ").append(toIndentedString(instance)).append("\n");
    sb.append("    formData: ").append(toIndentedString(formData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("id_base");
    openapiFields.add("sidebar");
    openapiFields.add("rendered");
    openapiFields.add("rendered_form");
    openapiFields.add("instance");
    openapiFields.add("form_data");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Widget
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Widget.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Widget is not found in the empty JSON string", Widget.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Widget.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `Widget` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if ((jsonObj.get("id_base") != null && !jsonObj.get("id_base").isJsonNull()) && !jsonObj.get("id_base").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id_base` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id_base").toString()));
      }
      if ((jsonObj.get("sidebar") != null && !jsonObj.get("sidebar").isJsonNull()) && !jsonObj.get("sidebar").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `sidebar` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sidebar").toString()));
      }
      if ((jsonObj.get("rendered") != null && !jsonObj.get("rendered").isJsonNull()) && !jsonObj.get("rendered").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `rendered` to be a primitive type in the JSON string but got `%s`", jsonObj.get("rendered").toString()));
      }
      if ((jsonObj.get("rendered_form") != null && !jsonObj.get("rendered_form").isJsonNull()) && !jsonObj.get("rendered_form").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `rendered_form` to be a primitive type in the JSON string but got `%s`", jsonObj.get("rendered_form").toString()));
      }
      // validate the optional field `instance`
      if (jsonObj.get("instance") != null && !jsonObj.get("instance").isJsonNull()) {
        WidgetsPostRequestInstance.validateJsonElement(jsonObj.get("instance"));
      }
      if ((jsonObj.get("form_data") != null && !jsonObj.get("form_data").isJsonNull()) && !jsonObj.get("form_data").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `form_data` to be a primitive type in the JSON string but got `%s`", jsonObj.get("form_data").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Widget.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Widget' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Widget> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Widget.class));

       return (TypeAdapter<T>) new TypeAdapter<Widget>() {
           @Override
           public void write(JsonWriter out, Widget value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Widget read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Widget given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Widget
   * @throws IOException if the JSON string is invalid with respect to Widget
   */
  public static Widget fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Widget.class);
  }

  /**
   * Convert an instance of Widget to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

