/*
 * WordPress REST API
 * The WordPress REST API is a powerful part of WordPress that lets you read and write various parts of WordPress data such as posts, pages, users, media, categories, tags, and custom content types defined in the installation.
 *
 * The version of the OpenAPI document: v2
 * Contact: labs@wtx.pl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pl.wtx.wordpress.api.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.net.URI;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import pl.wtx.wordpress.api.client.model.BlocksPostRequestContent;
import pl.wtx.wordpress.api.client.model.BlocksPostRequestMeta;
import pl.wtx.wordpress.api.client.model.BlocksPostRequestTitle;
import pl.wtx.wordpress.api.client.model.PostGuid;
import pl.wtx.wordpress.api.client.model.PostsPostRequestExcerpt;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import pl.wtx.wordpress.api.client.invoker.JSON;

/**
 * Wpblock
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class Wpblock {
  public static final String SERIALIZED_NAME_DATE = "date";
  @SerializedName(SERIALIZED_NAME_DATE)
  @javax.annotation.Nullable
  private OffsetDateTime date;

  public static final String SERIALIZED_NAME_DATE_GMT = "date_gmt";
  @SerializedName(SERIALIZED_NAME_DATE_GMT)
  @javax.annotation.Nullable
  private OffsetDateTime dateGmt;

  public static final String SERIALIZED_NAME_GUID = "guid";
  @SerializedName(SERIALIZED_NAME_GUID)
  @javax.annotation.Nullable
  private PostGuid guid;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private Integer id;

  public static final String SERIALIZED_NAME_LINK = "link";
  @SerializedName(SERIALIZED_NAME_LINK)
  @javax.annotation.Nullable
  private URI link;

  public static final String SERIALIZED_NAME_MODIFIED = "modified";
  @SerializedName(SERIALIZED_NAME_MODIFIED)
  @javax.annotation.Nullable
  private OffsetDateTime modified;

  public static final String SERIALIZED_NAME_MODIFIED_GMT = "modified_gmt";
  @SerializedName(SERIALIZED_NAME_MODIFIED_GMT)
  @javax.annotation.Nullable
  private OffsetDateTime modifiedGmt;

  public static final String SERIALIZED_NAME_SLUG = "slug";
  @SerializedName(SERIALIZED_NAME_SLUG)
  @javax.annotation.Nullable
  private String slug;

  /**
   * A named status for the post.
   */
  @JsonAdapter(StatusEnum.Adapter.class)
  public enum StatusEnum {
    PUBLISH("publish"),
    
    FUTURE("future"),
    
    DRAFT("draft"),
    
    PENDING("pending"),
    
    PRIVATE("private");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return StatusEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      StatusEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nullable
  private StatusEnum status;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  @javax.annotation.Nullable
  private String type;

  public static final String SERIALIZED_NAME_PASSWORD = "password";
  @SerializedName(SERIALIZED_NAME_PASSWORD)
  @javax.annotation.Nullable
  private String password;

  public static final String SERIALIZED_NAME_TITLE = "title";
  @SerializedName(SERIALIZED_NAME_TITLE)
  @javax.annotation.Nullable
  private BlocksPostRequestTitle title;

  public static final String SERIALIZED_NAME_CONTENT = "content";
  @SerializedName(SERIALIZED_NAME_CONTENT)
  @javax.annotation.Nullable
  private BlocksPostRequestContent content;

  public static final String SERIALIZED_NAME_EXCERPT = "excerpt";
  @SerializedName(SERIALIZED_NAME_EXCERPT)
  @javax.annotation.Nullable
  private PostsPostRequestExcerpt excerpt;

  public static final String SERIALIZED_NAME_META = "meta";
  @SerializedName(SERIALIZED_NAME_META)
  @javax.annotation.Nullable
  private BlocksPostRequestMeta meta;

  public static final String SERIALIZED_NAME_TEMPLATE = "template";
  @SerializedName(SERIALIZED_NAME_TEMPLATE)
  @javax.annotation.Nullable
  private String template;

  public static final String SERIALIZED_NAME_WP_PATTERN_CATEGORY = "wp_pattern_category";
  @SerializedName(SERIALIZED_NAME_WP_PATTERN_CATEGORY)
  @javax.annotation.Nullable
  private List<Integer> wpPatternCategory = new ArrayList<>();

  public Wpblock() {
  }

  public Wpblock date(@javax.annotation.Nullable OffsetDateTime date) {
    this.date = date;
    return this;
  }

  /**
   * The date the post was published, in the site&#39;s timezone.
   * @return date
   */
  @javax.annotation.Nullable
  public OffsetDateTime getDate() {
    return date;
  }

  public void setDate(@javax.annotation.Nullable OffsetDateTime date) {
    this.date = date;
  }


  public Wpblock dateGmt(@javax.annotation.Nullable OffsetDateTime dateGmt) {
    this.dateGmt = dateGmt;
    return this;
  }

  /**
   * The date the post was published, as GMT.
   * @return dateGmt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getDateGmt() {
    return dateGmt;
  }

  public void setDateGmt(@javax.annotation.Nullable OffsetDateTime dateGmt) {
    this.dateGmt = dateGmt;
  }


  public Wpblock guid(@javax.annotation.Nullable PostGuid guid) {
    this.guid = guid;
    return this;
  }

  /**
   * Get guid
   * @return guid
   */
  @javax.annotation.Nullable
  public PostGuid getGuid() {
    return guid;
  }

  public void setGuid(@javax.annotation.Nullable PostGuid guid) {
    this.guid = guid;
  }


  public Wpblock id(@javax.annotation.Nullable Integer id) {
    this.id = id;
    return this;
  }

  /**
   * Unique identifier for the post.
   * @return id
   */
  @javax.annotation.Nullable
  public Integer getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable Integer id) {
    this.id = id;
  }


  public Wpblock link(@javax.annotation.Nullable URI link) {
    this.link = link;
    return this;
  }

  /**
   * URL to the post.
   * @return link
   */
  @javax.annotation.Nullable
  public URI getLink() {
    return link;
  }

  public void setLink(@javax.annotation.Nullable URI link) {
    this.link = link;
  }


  public Wpblock modified(@javax.annotation.Nullable OffsetDateTime modified) {
    this.modified = modified;
    return this;
  }

  /**
   * The date the post was last modified, in the site&#39;s timezone.
   * @return modified
   */
  @javax.annotation.Nullable
  public OffsetDateTime getModified() {
    return modified;
  }

  public void setModified(@javax.annotation.Nullable OffsetDateTime modified) {
    this.modified = modified;
  }


  public Wpblock modifiedGmt(@javax.annotation.Nullable OffsetDateTime modifiedGmt) {
    this.modifiedGmt = modifiedGmt;
    return this;
  }

  /**
   * The date the post was last modified, as GMT.
   * @return modifiedGmt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getModifiedGmt() {
    return modifiedGmt;
  }

  public void setModifiedGmt(@javax.annotation.Nullable OffsetDateTime modifiedGmt) {
    this.modifiedGmt = modifiedGmt;
  }


  public Wpblock slug(@javax.annotation.Nullable String slug) {
    this.slug = slug;
    return this;
  }

  /**
   * An alphanumeric identifier for the post unique to its type.
   * @return slug
   */
  @javax.annotation.Nullable
  public String getSlug() {
    return slug;
  }

  public void setSlug(@javax.annotation.Nullable String slug) {
    this.slug = slug;
  }


  public Wpblock status(@javax.annotation.Nullable StatusEnum status) {
    this.status = status;
    return this;
  }

  /**
   * A named status for the post.
   * @return status
   */
  @javax.annotation.Nullable
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nullable StatusEnum status) {
    this.status = status;
  }


  public Wpblock type(@javax.annotation.Nullable String type) {
    this.type = type;
    return this;
  }

  /**
   * Type of post.
   * @return type
   */
  @javax.annotation.Nullable
  public String getType() {
    return type;
  }

  public void setType(@javax.annotation.Nullable String type) {
    this.type = type;
  }


  public Wpblock password(@javax.annotation.Nullable String password) {
    this.password = password;
    return this;
  }

  /**
   * A password to protect access to the content and excerpt.
   * @return password
   */
  @javax.annotation.Nullable
  public String getPassword() {
    return password;
  }

  public void setPassword(@javax.annotation.Nullable String password) {
    this.password = password;
  }


  public Wpblock title(@javax.annotation.Nullable BlocksPostRequestTitle title) {
    this.title = title;
    return this;
  }

  /**
   * Get title
   * @return title
   */
  @javax.annotation.Nullable
  public BlocksPostRequestTitle getTitle() {
    return title;
  }

  public void setTitle(@javax.annotation.Nullable BlocksPostRequestTitle title) {
    this.title = title;
  }


  public Wpblock content(@javax.annotation.Nullable BlocksPostRequestContent content) {
    this.content = content;
    return this;
  }

  /**
   * Get content
   * @return content
   */
  @javax.annotation.Nullable
  public BlocksPostRequestContent getContent() {
    return content;
  }

  public void setContent(@javax.annotation.Nullable BlocksPostRequestContent content) {
    this.content = content;
  }


  public Wpblock excerpt(@javax.annotation.Nullable PostsPostRequestExcerpt excerpt) {
    this.excerpt = excerpt;
    return this;
  }

  /**
   * Get excerpt
   * @return excerpt
   */
  @javax.annotation.Nullable
  public PostsPostRequestExcerpt getExcerpt() {
    return excerpt;
  }

  public void setExcerpt(@javax.annotation.Nullable PostsPostRequestExcerpt excerpt) {
    this.excerpt = excerpt;
  }


  public Wpblock meta(@javax.annotation.Nullable BlocksPostRequestMeta meta) {
    this.meta = meta;
    return this;
  }

  /**
   * Get meta
   * @return meta
   */
  @javax.annotation.Nullable
  public BlocksPostRequestMeta getMeta() {
    return meta;
  }

  public void setMeta(@javax.annotation.Nullable BlocksPostRequestMeta meta) {
    this.meta = meta;
  }


  public Wpblock template(@javax.annotation.Nullable String template) {
    this.template = template;
    return this;
  }

  /**
   * The theme file to use to display the post.
   * @return template
   */
  @javax.annotation.Nullable
  public String getTemplate() {
    return template;
  }

  public void setTemplate(@javax.annotation.Nullable String template) {
    this.template = template;
  }


  public Wpblock wpPatternCategory(@javax.annotation.Nullable List<Integer> wpPatternCategory) {
    this.wpPatternCategory = wpPatternCategory;
    return this;
  }

  public Wpblock addWpPatternCategoryItem(Integer wpPatternCategoryItem) {
    if (this.wpPatternCategory == null) {
      this.wpPatternCategory = new ArrayList<>();
    }
    this.wpPatternCategory.add(wpPatternCategoryItem);
    return this;
  }

  /**
   * The terms assigned to the post in the wp_pattern_category taxonomy.
   * @return wpPatternCategory
   */
  @javax.annotation.Nullable
  public List<Integer> getWpPatternCategory() {
    return wpPatternCategory;
  }

  public void setWpPatternCategory(@javax.annotation.Nullable List<Integer> wpPatternCategory) {
    this.wpPatternCategory = wpPatternCategory;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Wpblock wpblock = (Wpblock) o;
    return Objects.equals(this.date, wpblock.date) &&
        Objects.equals(this.dateGmt, wpblock.dateGmt) &&
        Objects.equals(this.guid, wpblock.guid) &&
        Objects.equals(this.id, wpblock.id) &&
        Objects.equals(this.link, wpblock.link) &&
        Objects.equals(this.modified, wpblock.modified) &&
        Objects.equals(this.modifiedGmt, wpblock.modifiedGmt) &&
        Objects.equals(this.slug, wpblock.slug) &&
        Objects.equals(this.status, wpblock.status) &&
        Objects.equals(this.type, wpblock.type) &&
        Objects.equals(this.password, wpblock.password) &&
        Objects.equals(this.title, wpblock.title) &&
        Objects.equals(this.content, wpblock.content) &&
        Objects.equals(this.excerpt, wpblock.excerpt) &&
        Objects.equals(this.meta, wpblock.meta) &&
        Objects.equals(this.template, wpblock.template) &&
        Objects.equals(this.wpPatternCategory, wpblock.wpPatternCategory);
  }

  @Override
  public int hashCode() {
    return Objects.hash(date, dateGmt, guid, id, link, modified, modifiedGmt, slug, status, type, password, title, content, excerpt, meta, template, wpPatternCategory);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Wpblock {\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    dateGmt: ").append(toIndentedString(dateGmt)).append("\n");
    sb.append("    guid: ").append(toIndentedString(guid)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    link: ").append(toIndentedString(link)).append("\n");
    sb.append("    modified: ").append(toIndentedString(modified)).append("\n");
    sb.append("    modifiedGmt: ").append(toIndentedString(modifiedGmt)).append("\n");
    sb.append("    slug: ").append(toIndentedString(slug)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    excerpt: ").append(toIndentedString(excerpt)).append("\n");
    sb.append("    meta: ").append(toIndentedString(meta)).append("\n");
    sb.append("    template: ").append(toIndentedString(template)).append("\n");
    sb.append("    wpPatternCategory: ").append(toIndentedString(wpPatternCategory)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("date");
    openapiFields.add("date_gmt");
    openapiFields.add("guid");
    openapiFields.add("id");
    openapiFields.add("link");
    openapiFields.add("modified");
    openapiFields.add("modified_gmt");
    openapiFields.add("slug");
    openapiFields.add("status");
    openapiFields.add("type");
    openapiFields.add("password");
    openapiFields.add("title");
    openapiFields.add("content");
    openapiFields.add("excerpt");
    openapiFields.add("meta");
    openapiFields.add("template");
    openapiFields.add("wp_pattern_category");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Wpblock
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Wpblock.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Wpblock is not found in the empty JSON string", Wpblock.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Wpblock.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `Wpblock` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `guid`
      if (jsonObj.get("guid") != null && !jsonObj.get("guid").isJsonNull()) {
        PostGuid.validateJsonElement(jsonObj.get("guid"));
      }
      if ((jsonObj.get("link") != null && !jsonObj.get("link").isJsonNull()) && !jsonObj.get("link").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `link` to be a primitive type in the JSON string but got `%s`", jsonObj.get("link").toString()));
      }
      if ((jsonObj.get("slug") != null && !jsonObj.get("slug").isJsonNull()) && !jsonObj.get("slug").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `slug` to be a primitive type in the JSON string but got `%s`", jsonObj.get("slug").toString()));
      }
      if ((jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) && !jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
      // validate the optional field `status`
      if (jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) {
        StatusEnum.validateJsonElement(jsonObj.get("status"));
      }
      if ((jsonObj.get("type") != null && !jsonObj.get("type").isJsonNull()) && !jsonObj.get("type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("type").toString()));
      }
      if ((jsonObj.get("password") != null && !jsonObj.get("password").isJsonNull()) && !jsonObj.get("password").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `password` to be a primitive type in the JSON string but got `%s`", jsonObj.get("password").toString()));
      }
      // validate the optional field `title`
      if (jsonObj.get("title") != null && !jsonObj.get("title").isJsonNull()) {
        BlocksPostRequestTitle.validateJsonElement(jsonObj.get("title"));
      }
      // validate the optional field `content`
      if (jsonObj.get("content") != null && !jsonObj.get("content").isJsonNull()) {
        BlocksPostRequestContent.validateJsonElement(jsonObj.get("content"));
      }
      // validate the optional field `excerpt`
      if (jsonObj.get("excerpt") != null && !jsonObj.get("excerpt").isJsonNull()) {
        PostsPostRequestExcerpt.validateJsonElement(jsonObj.get("excerpt"));
      }
      // validate the optional field `meta`
      if (jsonObj.get("meta") != null && !jsonObj.get("meta").isJsonNull()) {
        BlocksPostRequestMeta.validateJsonElement(jsonObj.get("meta"));
      }
      if ((jsonObj.get("template") != null && !jsonObj.get("template").isJsonNull()) && !jsonObj.get("template").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `template` to be a primitive type in the JSON string but got `%s`", jsonObj.get("template").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("wp_pattern_category") != null && !jsonObj.get("wp_pattern_category").isJsonNull() && !jsonObj.get("wp_pattern_category").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `wp_pattern_category` to be an array in the JSON string but got `%s`", jsonObj.get("wp_pattern_category").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Wpblock.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Wpblock' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Wpblock> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Wpblock.class));

       return (TypeAdapter<T>) new TypeAdapter<Wpblock>() {
           @Override
           public void write(JsonWriter out, Wpblock value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Wpblock read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Wpblock given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Wpblock
   * @throws IOException if the JSON string is invalid with respect to Wpblock
   */
  public static Wpblock fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Wpblock.class);
  }

  /**
   * Convert an instance of Wpblock to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

