/*
 * WordPress REST API
 * The WordPress REST API is a powerful part of WordPress that lets you read and write various parts of WordPress data such as posts, pages, users, media, categories, tags, and custom content types defined in the installation.
 *
 * The version of the OpenAPI document: v2
 * Contact: labs@wtx.pl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pl.wtx.wordpress.api.client.invoker.auth;

import pl.wtx.wordpress.api.client.invoker.Pair;
import pl.wtx.wordpress.api.client.invoker.ApiException;

import okhttp3.Credentials;

import java.net.URI;
import java.util.Map;
import java.util.List;

public class HttpBasicAuth implements Authentication {
    private String username;
    private String password;

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Override
    public void applyToParams(List<Pair> queryParams, Map<String, String> headerParams, Map<String, String> cookieParams,
                              String payload, String method, URI uri) throws ApiException {
        if (username == null && password == null) {
            return;
        }
        headerParams.put("Authorization", Credentials.basic(
            username == null ? "" : username,
            password == null ? "" : password));
    }
}
