/*
 * WordPress REST API
 * The WordPress REST API is a powerful part of WordPress that lets you read and write various parts of WordPress data such as posts, pages, users, media, categories, tags, and custom content types defined in the installation.
 *
 * The version of the OpenAPI document: v2
 * Contact: labs@wtx.pl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pl.wtx.wordpress.api.client;

import pl.wtx.wordpress.api.client.invoker.ApiCallback;
import pl.wtx.wordpress.api.client.invoker.ApiClient;
import pl.wtx.wordpress.api.client.invoker.ApiException;
import pl.wtx.wordpress.api.client.invoker.ApiResponse;
import pl.wtx.wordpress.api.client.invoker.Configuration;
import pl.wtx.wordpress.api.client.invoker.Pair;
import pl.wtx.wordpress.api.client.invoker.ProgressRequestBody;
import pl.wtx.wordpress.api.client.invoker.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import pl.wtx.wordpress.api.client.model.Blocktype;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class BlockTypesApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public BlockTypesApi() {
        this(Configuration.getDefaultApiClient());
    }

    public BlockTypesApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for blockTypesGet
     * @param context Scope under which the request is made; determines fields present in response. (optional, default to view)
     * @param namespace Block namespace. (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call blockTypesGetCall(@javax.annotation.Nullable String context, @javax.annotation.Nullable String namespace, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/block-types";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (context != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("context", context));
        }

        if (namespace != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("namespace", namespace));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "basicAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call blockTypesGetValidateBeforeCall(@javax.annotation.Nullable String context, @javax.annotation.Nullable String namespace, final ApiCallback _callback) throws ApiException {
        return blockTypesGetCall(context, namespace, _callback);

    }

    /**
     * 
     * 
     * @param context Scope under which the request is made; determines fields present in response. (optional, default to view)
     * @param namespace Block namespace. (optional)
     * @return List&lt;Blocktype&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public List<Blocktype> blockTypesGet(@javax.annotation.Nullable String context, @javax.annotation.Nullable String namespace) throws ApiException {
        ApiResponse<List<Blocktype>> localVarResp = blockTypesGetWithHttpInfo(context, namespace);
        return localVarResp.getData();
    }

    /**
     * 
     * 
     * @param context Scope under which the request is made; determines fields present in response. (optional, default to view)
     * @param namespace Block namespace. (optional)
     * @return ApiResponse&lt;List&lt;Blocktype&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<Blocktype>> blockTypesGetWithHttpInfo(@javax.annotation.Nullable String context, @javax.annotation.Nullable String namespace) throws ApiException {
        okhttp3.Call localVarCall = blockTypesGetValidateBeforeCall(context, namespace, null);
        Type localVarReturnType = new TypeToken<List<Blocktype>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * 
     * @param context Scope under which the request is made; determines fields present in response. (optional, default to view)
     * @param namespace Block namespace. (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call blockTypesGetAsync(@javax.annotation.Nullable String context, @javax.annotation.Nullable String namespace, final ApiCallback<List<Blocktype>> _callback) throws ApiException {

        okhttp3.Call localVarCall = blockTypesGetValidateBeforeCall(context, namespace, _callback);
        Type localVarReturnType = new TypeToken<List<Blocktype>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for blockTypesNamespaceGet
     * @param namespace Block namespace. (required)
     * @param context Scope under which the request is made; determines fields present in response. (optional, default to view)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call blockTypesNamespaceGetCall(@javax.annotation.Nonnull String namespace, @javax.annotation.Nullable String context, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/block-types/{namespace}"
            .replace("{" + "namespace" + "}", localVarApiClient.escapeString(namespace.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (context != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("context", context));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "basicAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call blockTypesNamespaceGetValidateBeforeCall(@javax.annotation.Nonnull String namespace, @javax.annotation.Nullable String context, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'namespace' is set
        if (namespace == null) {
            throw new ApiException("Missing the required parameter 'namespace' when calling blockTypesNamespaceGet(Async)");
        }

        return blockTypesNamespaceGetCall(namespace, context, _callback);

    }

    /**
     * 
     * 
     * @param namespace Block namespace. (required)
     * @param context Scope under which the request is made; determines fields present in response. (optional, default to view)
     * @return Blocktype
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public Blocktype blockTypesNamespaceGet(@javax.annotation.Nonnull String namespace, @javax.annotation.Nullable String context) throws ApiException {
        ApiResponse<Blocktype> localVarResp = blockTypesNamespaceGetWithHttpInfo(namespace, context);
        return localVarResp.getData();
    }

    /**
     * 
     * 
     * @param namespace Block namespace. (required)
     * @param context Scope under which the request is made; determines fields present in response. (optional, default to view)
     * @return ApiResponse&lt;Blocktype&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Blocktype> blockTypesNamespaceGetWithHttpInfo(@javax.annotation.Nonnull String namespace, @javax.annotation.Nullable String context) throws ApiException {
        okhttp3.Call localVarCall = blockTypesNamespaceGetValidateBeforeCall(namespace, context, null);
        Type localVarReturnType = new TypeToken<Blocktype>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * 
     * @param namespace Block namespace. (required)
     * @param context Scope under which the request is made; determines fields present in response. (optional, default to view)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call blockTypesNamespaceGetAsync(@javax.annotation.Nonnull String namespace, @javax.annotation.Nullable String context, final ApiCallback<Blocktype> _callback) throws ApiException {

        okhttp3.Call localVarCall = blockTypesNamespaceGetValidateBeforeCall(namespace, context, _callback);
        Type localVarReturnType = new TypeToken<Blocktype>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for blockTypesNamespaceNameGet
     * @param name Block name. (required)
     * @param namespace Block namespace. (required)
     * @param context Scope under which the request is made; determines fields present in response. (optional, default to view)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call blockTypesNamespaceNameGetCall(@javax.annotation.Nonnull String name, @javax.annotation.Nonnull String namespace, @javax.annotation.Nullable String context, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/block-types/{namespace}/{name}"
            .replace("{" + "name" + "}", localVarApiClient.escapeString(name.toString()))
            .replace("{" + "namespace" + "}", localVarApiClient.escapeString(namespace.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (context != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("context", context));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "basicAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call blockTypesNamespaceNameGetValidateBeforeCall(@javax.annotation.Nonnull String name, @javax.annotation.Nonnull String namespace, @javax.annotation.Nullable String context, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'name' is set
        if (name == null) {
            throw new ApiException("Missing the required parameter 'name' when calling blockTypesNamespaceNameGet(Async)");
        }

        // verify the required parameter 'namespace' is set
        if (namespace == null) {
            throw new ApiException("Missing the required parameter 'namespace' when calling blockTypesNamespaceNameGet(Async)");
        }

        return blockTypesNamespaceNameGetCall(name, namespace, context, _callback);

    }

    /**
     * 
     * 
     * @param name Block name. (required)
     * @param namespace Block namespace. (required)
     * @param context Scope under which the request is made; determines fields present in response. (optional, default to view)
     * @return Blocktype
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public Blocktype blockTypesNamespaceNameGet(@javax.annotation.Nonnull String name, @javax.annotation.Nonnull String namespace, @javax.annotation.Nullable String context) throws ApiException {
        ApiResponse<Blocktype> localVarResp = blockTypesNamespaceNameGetWithHttpInfo(name, namespace, context);
        return localVarResp.getData();
    }

    /**
     * 
     * 
     * @param name Block name. (required)
     * @param namespace Block namespace. (required)
     * @param context Scope under which the request is made; determines fields present in response. (optional, default to view)
     * @return ApiResponse&lt;Blocktype&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Blocktype> blockTypesNamespaceNameGetWithHttpInfo(@javax.annotation.Nonnull String name, @javax.annotation.Nonnull String namespace, @javax.annotation.Nullable String context) throws ApiException {
        okhttp3.Call localVarCall = blockTypesNamespaceNameGetValidateBeforeCall(name, namespace, context, null);
        Type localVarReturnType = new TypeToken<Blocktype>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * 
     * @param name Block name. (required)
     * @param namespace Block namespace. (required)
     * @param context Scope under which the request is made; determines fields present in response. (optional, default to view)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call blockTypesNamespaceNameGetAsync(@javax.annotation.Nonnull String name, @javax.annotation.Nonnull String namespace, @javax.annotation.Nullable String context, final ApiCallback<Blocktype> _callback) throws ApiException {

        okhttp3.Call localVarCall = blockTypesNamespaceNameGetValidateBeforeCall(name, namespace, context, _callback);
        Type localVarReturnType = new TypeToken<Blocktype>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
