/*
 * WordPress REST API
 * The WordPress REST API is a powerful part of WordPress that lets you read and write various parts of WordPress data such as posts, pages, users, media, categories, tags, and custom content types defined in the installation.
 *
 * The version of the OpenAPI document: v2
 * Contact: labs@wtx.pl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pl.wtx.wordpress.api.client;

import pl.wtx.wordpress.api.client.invoker.ApiCallback;
import pl.wtx.wordpress.api.client.invoker.ApiClient;
import pl.wtx.wordpress.api.client.invoker.ApiException;
import pl.wtx.wordpress.api.client.invoker.ApiResponse;
import pl.wtx.wordpress.api.client.invoker.Configuration;
import pl.wtx.wordpress.api.client.invoker.Pair;
import pl.wtx.wordpress.api.client.invoker.ProgressRequestBody;
import pl.wtx.wordpress.api.client.invoker.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import pl.wtx.wordpress.api.client.model.Navmenu;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class MenusApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public MenusApi() {
        this(Configuration.getDefaultApiClient());
    }

    public MenusApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for menusGet
     * @param context Scope under which the request is made; determines fields present in response. (optional, default to view)
     * @param page Current page of the collection. (optional, default to 1)
     * @param perPage Maximum number of items to be returned in result set. (optional, default to 10)
     * @param search Limit results to those matching a string. (optional)
     * @param exclude Ensure result set excludes specific IDs. (optional)
     * @param include Limit result set to specific IDs. (optional)
     * @param offset Offset the result set by a specific number of items. (optional)
     * @param order Order sort attribute ascending or descending. (optional, default to asc)
     * @param orderby Sort collection by term attribute. (optional, default to name)
     * @param hideEmpty Whether to hide terms not assigned to any posts. (optional)
     * @param post Limit result set to terms assigned to a specific post. (optional)
     * @param slug Limit result set to terms with one or more specific slugs. (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call menusGetCall(@javax.annotation.Nullable String context, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer perPage, @javax.annotation.Nullable String search, @javax.annotation.Nullable List<Integer> exclude, @javax.annotation.Nullable List<Integer> include, @javax.annotation.Nullable String offset, @javax.annotation.Nullable String order, @javax.annotation.Nullable String orderby, @javax.annotation.Nullable String hideEmpty, @javax.annotation.Nullable String post, @javax.annotation.Nullable List<String> slug, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/menus";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (context != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("context", context));
        }

        if (page != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("page", page));
        }

        if (perPage != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("per_page", perPage));
        }

        if (search != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("search", search));
        }

        if (exclude != null) {
            localVarCollectionQueryParams.addAll(localVarApiClient.parameterToPairs("multi", "exclude", exclude));
        }

        if (include != null) {
            localVarCollectionQueryParams.addAll(localVarApiClient.parameterToPairs("multi", "include", include));
        }

        if (offset != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("offset", offset));
        }

        if (order != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("order", order));
        }

        if (orderby != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("orderby", orderby));
        }

        if (hideEmpty != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("hide_empty", hideEmpty));
        }

        if (post != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("post", post));
        }

        if (slug != null) {
            localVarCollectionQueryParams.addAll(localVarApiClient.parameterToPairs("multi", "slug", slug));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "basicAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call menusGetValidateBeforeCall(@javax.annotation.Nullable String context, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer perPage, @javax.annotation.Nullable String search, @javax.annotation.Nullable List<Integer> exclude, @javax.annotation.Nullable List<Integer> include, @javax.annotation.Nullable String offset, @javax.annotation.Nullable String order, @javax.annotation.Nullable String orderby, @javax.annotation.Nullable String hideEmpty, @javax.annotation.Nullable String post, @javax.annotation.Nullable List<String> slug, final ApiCallback _callback) throws ApiException {
        return menusGetCall(context, page, perPage, search, exclude, include, offset, order, orderby, hideEmpty, post, slug, _callback);

    }

    /**
     * 
     * 
     * @param context Scope under which the request is made; determines fields present in response. (optional, default to view)
     * @param page Current page of the collection. (optional, default to 1)
     * @param perPage Maximum number of items to be returned in result set. (optional, default to 10)
     * @param search Limit results to those matching a string. (optional)
     * @param exclude Ensure result set excludes specific IDs. (optional)
     * @param include Limit result set to specific IDs. (optional)
     * @param offset Offset the result set by a specific number of items. (optional)
     * @param order Order sort attribute ascending or descending. (optional, default to asc)
     * @param orderby Sort collection by term attribute. (optional, default to name)
     * @param hideEmpty Whether to hide terms not assigned to any posts. (optional)
     * @param post Limit result set to terms assigned to a specific post. (optional)
     * @param slug Limit result set to terms with one or more specific slugs. (optional)
     * @return List&lt;Navmenu&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public List<Navmenu> menusGet(@javax.annotation.Nullable String context, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer perPage, @javax.annotation.Nullable String search, @javax.annotation.Nullable List<Integer> exclude, @javax.annotation.Nullable List<Integer> include, @javax.annotation.Nullable String offset, @javax.annotation.Nullable String order, @javax.annotation.Nullable String orderby, @javax.annotation.Nullable String hideEmpty, @javax.annotation.Nullable String post, @javax.annotation.Nullable List<String> slug) throws ApiException {
        ApiResponse<List<Navmenu>> localVarResp = menusGetWithHttpInfo(context, page, perPage, search, exclude, include, offset, order, orderby, hideEmpty, post, slug);
        return localVarResp.getData();
    }

    /**
     * 
     * 
     * @param context Scope under which the request is made; determines fields present in response. (optional, default to view)
     * @param page Current page of the collection. (optional, default to 1)
     * @param perPage Maximum number of items to be returned in result set. (optional, default to 10)
     * @param search Limit results to those matching a string. (optional)
     * @param exclude Ensure result set excludes specific IDs. (optional)
     * @param include Limit result set to specific IDs. (optional)
     * @param offset Offset the result set by a specific number of items. (optional)
     * @param order Order sort attribute ascending or descending. (optional, default to asc)
     * @param orderby Sort collection by term attribute. (optional, default to name)
     * @param hideEmpty Whether to hide terms not assigned to any posts. (optional)
     * @param post Limit result set to terms assigned to a specific post. (optional)
     * @param slug Limit result set to terms with one or more specific slugs. (optional)
     * @return ApiResponse&lt;List&lt;Navmenu&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<Navmenu>> menusGetWithHttpInfo(@javax.annotation.Nullable String context, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer perPage, @javax.annotation.Nullable String search, @javax.annotation.Nullable List<Integer> exclude, @javax.annotation.Nullable List<Integer> include, @javax.annotation.Nullable String offset, @javax.annotation.Nullable String order, @javax.annotation.Nullable String orderby, @javax.annotation.Nullable String hideEmpty, @javax.annotation.Nullable String post, @javax.annotation.Nullable List<String> slug) throws ApiException {
        okhttp3.Call localVarCall = menusGetValidateBeforeCall(context, page, perPage, search, exclude, include, offset, order, orderby, hideEmpty, post, slug, null);
        Type localVarReturnType = new TypeToken<List<Navmenu>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * 
     * @param context Scope under which the request is made; determines fields present in response. (optional, default to view)
     * @param page Current page of the collection. (optional, default to 1)
     * @param perPage Maximum number of items to be returned in result set. (optional, default to 10)
     * @param search Limit results to those matching a string. (optional)
     * @param exclude Ensure result set excludes specific IDs. (optional)
     * @param include Limit result set to specific IDs. (optional)
     * @param offset Offset the result set by a specific number of items. (optional)
     * @param order Order sort attribute ascending or descending. (optional, default to asc)
     * @param orderby Sort collection by term attribute. (optional, default to name)
     * @param hideEmpty Whether to hide terms not assigned to any posts. (optional)
     * @param post Limit result set to terms assigned to a specific post. (optional)
     * @param slug Limit result set to terms with one or more specific slugs. (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call menusGetAsync(@javax.annotation.Nullable String context, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer perPage, @javax.annotation.Nullable String search, @javax.annotation.Nullable List<Integer> exclude, @javax.annotation.Nullable List<Integer> include, @javax.annotation.Nullable String offset, @javax.annotation.Nullable String order, @javax.annotation.Nullable String orderby, @javax.annotation.Nullable String hideEmpty, @javax.annotation.Nullable String post, @javax.annotation.Nullable List<String> slug, final ApiCallback<List<Navmenu>> _callback) throws ApiException {

        okhttp3.Call localVarCall = menusGetValidateBeforeCall(context, page, perPage, search, exclude, include, offset, order, orderby, hideEmpty, post, slug, _callback);
        Type localVarReturnType = new TypeToken<List<Navmenu>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for menusIdDelete
     * @param id Unique identifier for the term. (required)
     * @param force Required to be true, as terms do not support trashing. (optional, default to false)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call menusIdDeleteCall(@javax.annotation.Nonnull String id, @javax.annotation.Nullable Boolean force, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/menus/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (force != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("force", force));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "basicAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call menusIdDeleteValidateBeforeCall(@javax.annotation.Nonnull String id, @javax.annotation.Nullable Boolean force, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling menusIdDelete(Async)");
        }

        return menusIdDeleteCall(id, force, _callback);

    }

    /**
     * 
     * 
     * @param id Unique identifier for the term. (required)
     * @param force Required to be true, as terms do not support trashing. (optional, default to false)
     * @return Navmenu
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public Navmenu menusIdDelete(@javax.annotation.Nonnull String id, @javax.annotation.Nullable Boolean force) throws ApiException {
        ApiResponse<Navmenu> localVarResp = menusIdDeleteWithHttpInfo(id, force);
        return localVarResp.getData();
    }

    /**
     * 
     * 
     * @param id Unique identifier for the term. (required)
     * @param force Required to be true, as terms do not support trashing. (optional, default to false)
     * @return ApiResponse&lt;Navmenu&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Navmenu> menusIdDeleteWithHttpInfo(@javax.annotation.Nonnull String id, @javax.annotation.Nullable Boolean force) throws ApiException {
        okhttp3.Call localVarCall = menusIdDeleteValidateBeforeCall(id, force, null);
        Type localVarReturnType = new TypeToken<Navmenu>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * 
     * @param id Unique identifier for the term. (required)
     * @param force Required to be true, as terms do not support trashing. (optional, default to false)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call menusIdDeleteAsync(@javax.annotation.Nonnull String id, @javax.annotation.Nullable Boolean force, final ApiCallback<Navmenu> _callback) throws ApiException {

        okhttp3.Call localVarCall = menusIdDeleteValidateBeforeCall(id, force, _callback);
        Type localVarReturnType = new TypeToken<Navmenu>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for menusIdGet
     * @param id Unique identifier for the term. (required)
     * @param context Scope under which the request is made; determines fields present in response. (optional, default to view)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call menusIdGetCall(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String context, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/menus/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (context != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("context", context));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "basicAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call menusIdGetValidateBeforeCall(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String context, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling menusIdGet(Async)");
        }

        return menusIdGetCall(id, context, _callback);

    }

    /**
     * 
     * 
     * @param id Unique identifier for the term. (required)
     * @param context Scope under which the request is made; determines fields present in response. (optional, default to view)
     * @return Navmenu
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public Navmenu menusIdGet(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String context) throws ApiException {
        ApiResponse<Navmenu> localVarResp = menusIdGetWithHttpInfo(id, context);
        return localVarResp.getData();
    }

    /**
     * 
     * 
     * @param id Unique identifier for the term. (required)
     * @param context Scope under which the request is made; determines fields present in response. (optional, default to view)
     * @return ApiResponse&lt;Navmenu&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Navmenu> menusIdGetWithHttpInfo(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String context) throws ApiException {
        okhttp3.Call localVarCall = menusIdGetValidateBeforeCall(id, context, null);
        Type localVarReturnType = new TypeToken<Navmenu>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * 
     * @param id Unique identifier for the term. (required)
     * @param context Scope under which the request is made; determines fields present in response. (optional, default to view)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call menusIdGetAsync(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String context, final ApiCallback<Navmenu> _callback) throws ApiException {

        okhttp3.Call localVarCall = menusIdGetValidateBeforeCall(id, context, _callback);
        Type localVarReturnType = new TypeToken<Navmenu>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for menusIdPatch
     * @param id Unique identifier for the term. (required)
     * @param description HTML description of the term. (optional)
     * @param name HTML title for the term. (optional)
     * @param slug An alphanumeric identifier for the term unique to its type. (optional)
     * @param meta Meta fields. (optional)
     * @param locations The locations assigned to the menu. (optional)
     * @param autoAdd Whether to automatically add top level pages to this menu. (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call menusIdPatchCall(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String description, @javax.annotation.Nullable String name, @javax.annotation.Nullable String slug, @javax.annotation.Nullable Object meta, @javax.annotation.Nullable List<String> locations, @javax.annotation.Nullable Boolean autoAdd, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/menus/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (description != null) {
            localVarFormParams.put("description", description);
        }

        if (name != null) {
            localVarFormParams.put("name", name);
        }

        if (slug != null) {
            localVarFormParams.put("slug", slug);
        }

        if (meta != null) {
            localVarFormParams.put("meta", meta);
        }

        if (locations != null) {
            localVarFormParams.put("locations", locations);
        }

        if (autoAdd != null) {
            localVarFormParams.put("auto_add", autoAdd);
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/x-www-form-urlencoded"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "basicAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "PATCH", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call menusIdPatchValidateBeforeCall(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String description, @javax.annotation.Nullable String name, @javax.annotation.Nullable String slug, @javax.annotation.Nullable Object meta, @javax.annotation.Nullable List<String> locations, @javax.annotation.Nullable Boolean autoAdd, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling menusIdPatch(Async)");
        }

        return menusIdPatchCall(id, description, name, slug, meta, locations, autoAdd, _callback);

    }

    /**
     * 
     * 
     * @param id Unique identifier for the term. (required)
     * @param description HTML description of the term. (optional)
     * @param name HTML title for the term. (optional)
     * @param slug An alphanumeric identifier for the term unique to its type. (optional)
     * @param meta Meta fields. (optional)
     * @param locations The locations assigned to the menu. (optional)
     * @param autoAdd Whether to automatically add top level pages to this menu. (optional)
     * @return Navmenu
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public Navmenu menusIdPatch(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String description, @javax.annotation.Nullable String name, @javax.annotation.Nullable String slug, @javax.annotation.Nullable Object meta, @javax.annotation.Nullable List<String> locations, @javax.annotation.Nullable Boolean autoAdd) throws ApiException {
        ApiResponse<Navmenu> localVarResp = menusIdPatchWithHttpInfo(id, description, name, slug, meta, locations, autoAdd);
        return localVarResp.getData();
    }

    /**
     * 
     * 
     * @param id Unique identifier for the term. (required)
     * @param description HTML description of the term. (optional)
     * @param name HTML title for the term. (optional)
     * @param slug An alphanumeric identifier for the term unique to its type. (optional)
     * @param meta Meta fields. (optional)
     * @param locations The locations assigned to the menu. (optional)
     * @param autoAdd Whether to automatically add top level pages to this menu. (optional)
     * @return ApiResponse&lt;Navmenu&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Navmenu> menusIdPatchWithHttpInfo(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String description, @javax.annotation.Nullable String name, @javax.annotation.Nullable String slug, @javax.annotation.Nullable Object meta, @javax.annotation.Nullable List<String> locations, @javax.annotation.Nullable Boolean autoAdd) throws ApiException {
        okhttp3.Call localVarCall = menusIdPatchValidateBeforeCall(id, description, name, slug, meta, locations, autoAdd, null);
        Type localVarReturnType = new TypeToken<Navmenu>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * 
     * @param id Unique identifier for the term. (required)
     * @param description HTML description of the term. (optional)
     * @param name HTML title for the term. (optional)
     * @param slug An alphanumeric identifier for the term unique to its type. (optional)
     * @param meta Meta fields. (optional)
     * @param locations The locations assigned to the menu. (optional)
     * @param autoAdd Whether to automatically add top level pages to this menu. (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call menusIdPatchAsync(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String description, @javax.annotation.Nullable String name, @javax.annotation.Nullable String slug, @javax.annotation.Nullable Object meta, @javax.annotation.Nullable List<String> locations, @javax.annotation.Nullable Boolean autoAdd, final ApiCallback<Navmenu> _callback) throws ApiException {

        okhttp3.Call localVarCall = menusIdPatchValidateBeforeCall(id, description, name, slug, meta, locations, autoAdd, _callback);
        Type localVarReturnType = new TypeToken<Navmenu>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for menusIdPost
     * @param id Unique identifier for the term. (required)
     * @param description HTML description of the term. (optional)
     * @param name HTML title for the term. (optional)
     * @param slug An alphanumeric identifier for the term unique to its type. (optional)
     * @param meta Meta fields. (optional)
     * @param locations The locations assigned to the menu. (optional)
     * @param autoAdd Whether to automatically add top level pages to this menu. (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call menusIdPostCall(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String description, @javax.annotation.Nullable String name, @javax.annotation.Nullable String slug, @javax.annotation.Nullable Object meta, @javax.annotation.Nullable List<String> locations, @javax.annotation.Nullable Boolean autoAdd, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/menus/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (description != null) {
            localVarFormParams.put("description", description);
        }

        if (name != null) {
            localVarFormParams.put("name", name);
        }

        if (slug != null) {
            localVarFormParams.put("slug", slug);
        }

        if (meta != null) {
            localVarFormParams.put("meta", meta);
        }

        if (locations != null) {
            localVarFormParams.put("locations", locations);
        }

        if (autoAdd != null) {
            localVarFormParams.put("auto_add", autoAdd);
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/x-www-form-urlencoded"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "basicAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call menusIdPostValidateBeforeCall(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String description, @javax.annotation.Nullable String name, @javax.annotation.Nullable String slug, @javax.annotation.Nullable Object meta, @javax.annotation.Nullable List<String> locations, @javax.annotation.Nullable Boolean autoAdd, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling menusIdPost(Async)");
        }

        return menusIdPostCall(id, description, name, slug, meta, locations, autoAdd, _callback);

    }

    /**
     * 
     * 
     * @param id Unique identifier for the term. (required)
     * @param description HTML description of the term. (optional)
     * @param name HTML title for the term. (optional)
     * @param slug An alphanumeric identifier for the term unique to its type. (optional)
     * @param meta Meta fields. (optional)
     * @param locations The locations assigned to the menu. (optional)
     * @param autoAdd Whether to automatically add top level pages to this menu. (optional)
     * @return Navmenu
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public Navmenu menusIdPost(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String description, @javax.annotation.Nullable String name, @javax.annotation.Nullable String slug, @javax.annotation.Nullable Object meta, @javax.annotation.Nullable List<String> locations, @javax.annotation.Nullable Boolean autoAdd) throws ApiException {
        ApiResponse<Navmenu> localVarResp = menusIdPostWithHttpInfo(id, description, name, slug, meta, locations, autoAdd);
        return localVarResp.getData();
    }

    /**
     * 
     * 
     * @param id Unique identifier for the term. (required)
     * @param description HTML description of the term. (optional)
     * @param name HTML title for the term. (optional)
     * @param slug An alphanumeric identifier for the term unique to its type. (optional)
     * @param meta Meta fields. (optional)
     * @param locations The locations assigned to the menu. (optional)
     * @param autoAdd Whether to automatically add top level pages to this menu. (optional)
     * @return ApiResponse&lt;Navmenu&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Navmenu> menusIdPostWithHttpInfo(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String description, @javax.annotation.Nullable String name, @javax.annotation.Nullable String slug, @javax.annotation.Nullable Object meta, @javax.annotation.Nullable List<String> locations, @javax.annotation.Nullable Boolean autoAdd) throws ApiException {
        okhttp3.Call localVarCall = menusIdPostValidateBeforeCall(id, description, name, slug, meta, locations, autoAdd, null);
        Type localVarReturnType = new TypeToken<Navmenu>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * 
     * @param id Unique identifier for the term. (required)
     * @param description HTML description of the term. (optional)
     * @param name HTML title for the term. (optional)
     * @param slug An alphanumeric identifier for the term unique to its type. (optional)
     * @param meta Meta fields. (optional)
     * @param locations The locations assigned to the menu. (optional)
     * @param autoAdd Whether to automatically add top level pages to this menu. (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call menusIdPostAsync(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String description, @javax.annotation.Nullable String name, @javax.annotation.Nullable String slug, @javax.annotation.Nullable Object meta, @javax.annotation.Nullable List<String> locations, @javax.annotation.Nullable Boolean autoAdd, final ApiCallback<Navmenu> _callback) throws ApiException {

        okhttp3.Call localVarCall = menusIdPostValidateBeforeCall(id, description, name, slug, meta, locations, autoAdd, _callback);
        Type localVarReturnType = new TypeToken<Navmenu>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for menusIdPut
     * @param id Unique identifier for the term. (required)
     * @param description HTML description of the term. (optional)
     * @param name HTML title for the term. (optional)
     * @param slug An alphanumeric identifier for the term unique to its type. (optional)
     * @param meta Meta fields. (optional)
     * @param locations The locations assigned to the menu. (optional)
     * @param autoAdd Whether to automatically add top level pages to this menu. (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call menusIdPutCall(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String description, @javax.annotation.Nullable String name, @javax.annotation.Nullable String slug, @javax.annotation.Nullable Object meta, @javax.annotation.Nullable List<String> locations, @javax.annotation.Nullable Boolean autoAdd, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/menus/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (description != null) {
            localVarFormParams.put("description", description);
        }

        if (name != null) {
            localVarFormParams.put("name", name);
        }

        if (slug != null) {
            localVarFormParams.put("slug", slug);
        }

        if (meta != null) {
            localVarFormParams.put("meta", meta);
        }

        if (locations != null) {
            localVarFormParams.put("locations", locations);
        }

        if (autoAdd != null) {
            localVarFormParams.put("auto_add", autoAdd);
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/x-www-form-urlencoded"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "basicAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call menusIdPutValidateBeforeCall(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String description, @javax.annotation.Nullable String name, @javax.annotation.Nullable String slug, @javax.annotation.Nullable Object meta, @javax.annotation.Nullable List<String> locations, @javax.annotation.Nullable Boolean autoAdd, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling menusIdPut(Async)");
        }

        return menusIdPutCall(id, description, name, slug, meta, locations, autoAdd, _callback);

    }

    /**
     * 
     * 
     * @param id Unique identifier for the term. (required)
     * @param description HTML description of the term. (optional)
     * @param name HTML title for the term. (optional)
     * @param slug An alphanumeric identifier for the term unique to its type. (optional)
     * @param meta Meta fields. (optional)
     * @param locations The locations assigned to the menu. (optional)
     * @param autoAdd Whether to automatically add top level pages to this menu. (optional)
     * @return Navmenu
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public Navmenu menusIdPut(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String description, @javax.annotation.Nullable String name, @javax.annotation.Nullable String slug, @javax.annotation.Nullable Object meta, @javax.annotation.Nullable List<String> locations, @javax.annotation.Nullable Boolean autoAdd) throws ApiException {
        ApiResponse<Navmenu> localVarResp = menusIdPutWithHttpInfo(id, description, name, slug, meta, locations, autoAdd);
        return localVarResp.getData();
    }

    /**
     * 
     * 
     * @param id Unique identifier for the term. (required)
     * @param description HTML description of the term. (optional)
     * @param name HTML title for the term. (optional)
     * @param slug An alphanumeric identifier for the term unique to its type. (optional)
     * @param meta Meta fields. (optional)
     * @param locations The locations assigned to the menu. (optional)
     * @param autoAdd Whether to automatically add top level pages to this menu. (optional)
     * @return ApiResponse&lt;Navmenu&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Navmenu> menusIdPutWithHttpInfo(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String description, @javax.annotation.Nullable String name, @javax.annotation.Nullable String slug, @javax.annotation.Nullable Object meta, @javax.annotation.Nullable List<String> locations, @javax.annotation.Nullable Boolean autoAdd) throws ApiException {
        okhttp3.Call localVarCall = menusIdPutValidateBeforeCall(id, description, name, slug, meta, locations, autoAdd, null);
        Type localVarReturnType = new TypeToken<Navmenu>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * 
     * @param id Unique identifier for the term. (required)
     * @param description HTML description of the term. (optional)
     * @param name HTML title for the term. (optional)
     * @param slug An alphanumeric identifier for the term unique to its type. (optional)
     * @param meta Meta fields. (optional)
     * @param locations The locations assigned to the menu. (optional)
     * @param autoAdd Whether to automatically add top level pages to this menu. (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call menusIdPutAsync(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String description, @javax.annotation.Nullable String name, @javax.annotation.Nullable String slug, @javax.annotation.Nullable Object meta, @javax.annotation.Nullable List<String> locations, @javax.annotation.Nullable Boolean autoAdd, final ApiCallback<Navmenu> _callback) throws ApiException {

        okhttp3.Call localVarCall = menusIdPutValidateBeforeCall(id, description, name, slug, meta, locations, autoAdd, _callback);
        Type localVarReturnType = new TypeToken<Navmenu>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for menusPost
     * @param name HTML title for the term. (required)
     * @param description HTML description of the term. (optional)
     * @param slug An alphanumeric identifier for the term unique to its type. (optional)
     * @param meta Meta fields. (optional)
     * @param locations The locations assigned to the menu. (optional)
     * @param autoAdd Whether to automatically add top level pages to this menu. (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call menusPostCall(@javax.annotation.Nonnull String name, @javax.annotation.Nullable String description, @javax.annotation.Nullable String slug, @javax.annotation.Nullable Object meta, @javax.annotation.Nullable List<String> locations, @javax.annotation.Nullable Boolean autoAdd, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/menus";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (description != null) {
            localVarFormParams.put("description", description);
        }

        if (name != null) {
            localVarFormParams.put("name", name);
        }

        if (slug != null) {
            localVarFormParams.put("slug", slug);
        }

        if (meta != null) {
            localVarFormParams.put("meta", meta);
        }

        if (locations != null) {
            localVarFormParams.put("locations", locations);
        }

        if (autoAdd != null) {
            localVarFormParams.put("auto_add", autoAdd);
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/x-www-form-urlencoded"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "basicAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call menusPostValidateBeforeCall(@javax.annotation.Nonnull String name, @javax.annotation.Nullable String description, @javax.annotation.Nullable String slug, @javax.annotation.Nullable Object meta, @javax.annotation.Nullable List<String> locations, @javax.annotation.Nullable Boolean autoAdd, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'name' is set
        if (name == null) {
            throw new ApiException("Missing the required parameter 'name' when calling menusPost(Async)");
        }

        return menusPostCall(name, description, slug, meta, locations, autoAdd, _callback);

    }

    /**
     * 
     * 
     * @param name HTML title for the term. (required)
     * @param description HTML description of the term. (optional)
     * @param slug An alphanumeric identifier for the term unique to its type. (optional)
     * @param meta Meta fields. (optional)
     * @param locations The locations assigned to the menu. (optional)
     * @param autoAdd Whether to automatically add top level pages to this menu. (optional)
     * @return Navmenu
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public Navmenu menusPost(@javax.annotation.Nonnull String name, @javax.annotation.Nullable String description, @javax.annotation.Nullable String slug, @javax.annotation.Nullable Object meta, @javax.annotation.Nullable List<String> locations, @javax.annotation.Nullable Boolean autoAdd) throws ApiException {
        ApiResponse<Navmenu> localVarResp = menusPostWithHttpInfo(name, description, slug, meta, locations, autoAdd);
        return localVarResp.getData();
    }

    /**
     * 
     * 
     * @param name HTML title for the term. (required)
     * @param description HTML description of the term. (optional)
     * @param slug An alphanumeric identifier for the term unique to its type. (optional)
     * @param meta Meta fields. (optional)
     * @param locations The locations assigned to the menu. (optional)
     * @param autoAdd Whether to automatically add top level pages to this menu. (optional)
     * @return ApiResponse&lt;Navmenu&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Navmenu> menusPostWithHttpInfo(@javax.annotation.Nonnull String name, @javax.annotation.Nullable String description, @javax.annotation.Nullable String slug, @javax.annotation.Nullable Object meta, @javax.annotation.Nullable List<String> locations, @javax.annotation.Nullable Boolean autoAdd) throws ApiException {
        okhttp3.Call localVarCall = menusPostValidateBeforeCall(name, description, slug, meta, locations, autoAdd, null);
        Type localVarReturnType = new TypeToken<Navmenu>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * 
     * @param name HTML title for the term. (required)
     * @param description HTML description of the term. (optional)
     * @param slug An alphanumeric identifier for the term unique to its type. (optional)
     * @param meta Meta fields. (optional)
     * @param locations The locations assigned to the menu. (optional)
     * @param autoAdd Whether to automatically add top level pages to this menu. (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call menusPostAsync(@javax.annotation.Nonnull String name, @javax.annotation.Nullable String description, @javax.annotation.Nullable String slug, @javax.annotation.Nullable Object meta, @javax.annotation.Nullable List<String> locations, @javax.annotation.Nullable Boolean autoAdd, final ApiCallback<Navmenu> _callback) throws ApiException {

        okhttp3.Call localVarCall = menusPostValidateBeforeCall(name, description, slug, meta, locations, autoAdd, _callback);
        Type localVarReturnType = new TypeToken<Navmenu>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
