/*
 * WordPress REST API
 * The WordPress REST API is a powerful part of WordPress that lets you read and write various parts of WordPress data such as posts, pages, users, media, categories, tags, and custom content types defined in the installation.
 *
 * The version of the OpenAPI document: v2
 * Contact: labs@wtx.pl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pl.wtx.wordpress.api.client;

import pl.wtx.wordpress.api.client.invoker.ApiCallback;
import pl.wtx.wordpress.api.client.invoker.ApiClient;
import pl.wtx.wordpress.api.client.invoker.ApiException;
import pl.wtx.wordpress.api.client.invoker.ApiResponse;
import pl.wtx.wordpress.api.client.invoker.Configuration;
import pl.wtx.wordpress.api.client.invoker.Pair;
import pl.wtx.wordpress.api.client.invoker.ProgressRequestBody;
import pl.wtx.wordpress.api.client.invoker.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import pl.wtx.wordpress.api.client.model.Searchresult;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class SearchApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public SearchApi() {
        this(Configuration.getDefaultApiClient());
    }

    public SearchApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for searchGet
     * @param context Scope under which the request is made; determines fields present in response. (optional, default to view)
     * @param page Current page of the collection. (optional, default to 1)
     * @param perPage Maximum number of items to be returned in result set. (optional, default to 10)
     * @param search Limit results to those matching a string. (optional)
     * @param type Limit results to items of an object type. (optional, default to post)
     * @param subtype Limit results to items of one or more object subtypes. (optional)
     * @param exclude Ensure result set excludes specific IDs. (optional)
     * @param include Limit result set to specific IDs. (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call searchGetCall(@javax.annotation.Nullable String context, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer perPage, @javax.annotation.Nullable String search, @javax.annotation.Nullable String type, @javax.annotation.Nullable List<String> subtype, @javax.annotation.Nullable List<Integer> exclude, @javax.annotation.Nullable List<Integer> include, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/search";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (context != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("context", context));
        }

        if (page != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("page", page));
        }

        if (perPage != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("per_page", perPage));
        }

        if (search != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("search", search));
        }

        if (type != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("type", type));
        }

        if (subtype != null) {
            localVarCollectionQueryParams.addAll(localVarApiClient.parameterToPairs("multi", "subtype", subtype));
        }

        if (exclude != null) {
            localVarCollectionQueryParams.addAll(localVarApiClient.parameterToPairs("multi", "exclude", exclude));
        }

        if (include != null) {
            localVarCollectionQueryParams.addAll(localVarApiClient.parameterToPairs("multi", "include", include));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "basicAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call searchGetValidateBeforeCall(@javax.annotation.Nullable String context, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer perPage, @javax.annotation.Nullable String search, @javax.annotation.Nullable String type, @javax.annotation.Nullable List<String> subtype, @javax.annotation.Nullable List<Integer> exclude, @javax.annotation.Nullable List<Integer> include, final ApiCallback _callback) throws ApiException {
        return searchGetCall(context, page, perPage, search, type, subtype, exclude, include, _callback);

    }

    /**
     * 
     * 
     * @param context Scope under which the request is made; determines fields present in response. (optional, default to view)
     * @param page Current page of the collection. (optional, default to 1)
     * @param perPage Maximum number of items to be returned in result set. (optional, default to 10)
     * @param search Limit results to those matching a string. (optional)
     * @param type Limit results to items of an object type. (optional, default to post)
     * @param subtype Limit results to items of one or more object subtypes. (optional)
     * @param exclude Ensure result set excludes specific IDs. (optional)
     * @param include Limit result set to specific IDs. (optional)
     * @return List&lt;Searchresult&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public List<Searchresult> searchGet(@javax.annotation.Nullable String context, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer perPage, @javax.annotation.Nullable String search, @javax.annotation.Nullable String type, @javax.annotation.Nullable List<String> subtype, @javax.annotation.Nullable List<Integer> exclude, @javax.annotation.Nullable List<Integer> include) throws ApiException {
        ApiResponse<List<Searchresult>> localVarResp = searchGetWithHttpInfo(context, page, perPage, search, type, subtype, exclude, include);
        return localVarResp.getData();
    }

    /**
     * 
     * 
     * @param context Scope under which the request is made; determines fields present in response. (optional, default to view)
     * @param page Current page of the collection. (optional, default to 1)
     * @param perPage Maximum number of items to be returned in result set. (optional, default to 10)
     * @param search Limit results to those matching a string. (optional)
     * @param type Limit results to items of an object type. (optional, default to post)
     * @param subtype Limit results to items of one or more object subtypes. (optional)
     * @param exclude Ensure result set excludes specific IDs. (optional)
     * @param include Limit result set to specific IDs. (optional)
     * @return ApiResponse&lt;List&lt;Searchresult&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<Searchresult>> searchGetWithHttpInfo(@javax.annotation.Nullable String context, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer perPage, @javax.annotation.Nullable String search, @javax.annotation.Nullable String type, @javax.annotation.Nullable List<String> subtype, @javax.annotation.Nullable List<Integer> exclude, @javax.annotation.Nullable List<Integer> include) throws ApiException {
        okhttp3.Call localVarCall = searchGetValidateBeforeCall(context, page, perPage, search, type, subtype, exclude, include, null);
        Type localVarReturnType = new TypeToken<List<Searchresult>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * 
     * @param context Scope under which the request is made; determines fields present in response. (optional, default to view)
     * @param page Current page of the collection. (optional, default to 1)
     * @param perPage Maximum number of items to be returned in result set. (optional, default to 10)
     * @param search Limit results to those matching a string. (optional)
     * @param type Limit results to items of an object type. (optional, default to post)
     * @param subtype Limit results to items of one or more object subtypes. (optional)
     * @param exclude Ensure result set excludes specific IDs. (optional)
     * @param include Limit result set to specific IDs. (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call searchGetAsync(@javax.annotation.Nullable String context, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer perPage, @javax.annotation.Nullable String search, @javax.annotation.Nullable String type, @javax.annotation.Nullable List<String> subtype, @javax.annotation.Nullable List<Integer> exclude, @javax.annotation.Nullable List<Integer> include, final ApiCallback<List<Searchresult>> _callback) throws ApiException {

        okhttp3.Call localVarCall = searchGetValidateBeforeCall(context, page, perPage, search, type, subtype, exclude, include, _callback);
        Type localVarReturnType = new TypeToken<List<Searchresult>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
