/*
 * WordPress REST API
 * The WordPress REST API is a powerful part of WordPress that lets you read and write various parts of WordPress data such as posts, pages, users, media, categories, tags, and custom content types defined in the installation.
 *
 * The version of the OpenAPI document: v2
 * Contact: labs@wtx.pl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pl.wtx.wordpress.api.client;

import pl.wtx.wordpress.api.client.invoker.ApiCallback;
import pl.wtx.wordpress.api.client.invoker.ApiClient;
import pl.wtx.wordpress.api.client.invoker.ApiException;
import pl.wtx.wordpress.api.client.invoker.ApiResponse;
import pl.wtx.wordpress.api.client.invoker.Configuration;
import pl.wtx.wordpress.api.client.invoker.Pair;
import pl.wtx.wordpress.api.client.invoker.ProgressRequestBody;
import pl.wtx.wordpress.api.client.invoker.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import pl.wtx.wordpress.api.client.model.Sidebar;
import pl.wtx.wordpress.api.client.model.SidebarsIdPutRequestWidgetsInner;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class SidebarsApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public SidebarsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public SidebarsApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for sidebarsGet
     * @param context Scope under which the request is made; determines fields present in response. (optional, default to view)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call sidebarsGetCall(@javax.annotation.Nullable String context, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/sidebars";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (context != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("context", context));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "basicAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call sidebarsGetValidateBeforeCall(@javax.annotation.Nullable String context, final ApiCallback _callback) throws ApiException {
        return sidebarsGetCall(context, _callback);

    }

    /**
     * 
     * 
     * @param context Scope under which the request is made; determines fields present in response. (optional, default to view)
     * @return List&lt;Sidebar&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public List<Sidebar> sidebarsGet(@javax.annotation.Nullable String context) throws ApiException {
        ApiResponse<List<Sidebar>> localVarResp = sidebarsGetWithHttpInfo(context);
        return localVarResp.getData();
    }

    /**
     * 
     * 
     * @param context Scope under which the request is made; determines fields present in response. (optional, default to view)
     * @return ApiResponse&lt;List&lt;Sidebar&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<Sidebar>> sidebarsGetWithHttpInfo(@javax.annotation.Nullable String context) throws ApiException {
        okhttp3.Call localVarCall = sidebarsGetValidateBeforeCall(context, null);
        Type localVarReturnType = new TypeToken<List<Sidebar>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * 
     * @param context Scope under which the request is made; determines fields present in response. (optional, default to view)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call sidebarsGetAsync(@javax.annotation.Nullable String context, final ApiCallback<List<Sidebar>> _callback) throws ApiException {

        okhttp3.Call localVarCall = sidebarsGetValidateBeforeCall(context, _callback);
        Type localVarReturnType = new TypeToken<List<Sidebar>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for sidebarsIdGet
     * @param id The id of a registered sidebar (required)
     * @param context Scope under which the request is made; determines fields present in response. (optional, default to view)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call sidebarsIdGetCall(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String context, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/sidebars/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (context != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("context", context));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "basicAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call sidebarsIdGetValidateBeforeCall(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String context, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling sidebarsIdGet(Async)");
        }

        return sidebarsIdGetCall(id, context, _callback);

    }

    /**
     * 
     * 
     * @param id The id of a registered sidebar (required)
     * @param context Scope under which the request is made; determines fields present in response. (optional, default to view)
     * @return Sidebar
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public Sidebar sidebarsIdGet(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String context) throws ApiException {
        ApiResponse<Sidebar> localVarResp = sidebarsIdGetWithHttpInfo(id, context);
        return localVarResp.getData();
    }

    /**
     * 
     * 
     * @param id The id of a registered sidebar (required)
     * @param context Scope under which the request is made; determines fields present in response. (optional, default to view)
     * @return ApiResponse&lt;Sidebar&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Sidebar> sidebarsIdGetWithHttpInfo(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String context) throws ApiException {
        okhttp3.Call localVarCall = sidebarsIdGetValidateBeforeCall(id, context, null);
        Type localVarReturnType = new TypeToken<Sidebar>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * 
     * @param id The id of a registered sidebar (required)
     * @param context Scope under which the request is made; determines fields present in response. (optional, default to view)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call sidebarsIdGetAsync(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String context, final ApiCallback<Sidebar> _callback) throws ApiException {

        okhttp3.Call localVarCall = sidebarsIdGetValidateBeforeCall(id, context, _callback);
        Type localVarReturnType = new TypeToken<Sidebar>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for sidebarsIdPatch
     * @param id  (required)
     * @param widgets Nested widgets. (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call sidebarsIdPatchCall(@javax.annotation.Nonnull String id, @javax.annotation.Nullable List<SidebarsIdPutRequestWidgetsInner> widgets, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/sidebars/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (widgets != null) {
            localVarFormParams.put("widgets", widgets);
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/x-www-form-urlencoded"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "basicAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "PATCH", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call sidebarsIdPatchValidateBeforeCall(@javax.annotation.Nonnull String id, @javax.annotation.Nullable List<SidebarsIdPutRequestWidgetsInner> widgets, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling sidebarsIdPatch(Async)");
        }

        return sidebarsIdPatchCall(id, widgets, _callback);

    }

    /**
     * 
     * 
     * @param id  (required)
     * @param widgets Nested widgets. (optional)
     * @return Sidebar
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public Sidebar sidebarsIdPatch(@javax.annotation.Nonnull String id, @javax.annotation.Nullable List<SidebarsIdPutRequestWidgetsInner> widgets) throws ApiException {
        ApiResponse<Sidebar> localVarResp = sidebarsIdPatchWithHttpInfo(id, widgets);
        return localVarResp.getData();
    }

    /**
     * 
     * 
     * @param id  (required)
     * @param widgets Nested widgets. (optional)
     * @return ApiResponse&lt;Sidebar&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Sidebar> sidebarsIdPatchWithHttpInfo(@javax.annotation.Nonnull String id, @javax.annotation.Nullable List<SidebarsIdPutRequestWidgetsInner> widgets) throws ApiException {
        okhttp3.Call localVarCall = sidebarsIdPatchValidateBeforeCall(id, widgets, null);
        Type localVarReturnType = new TypeToken<Sidebar>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * 
     * @param id  (required)
     * @param widgets Nested widgets. (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call sidebarsIdPatchAsync(@javax.annotation.Nonnull String id, @javax.annotation.Nullable List<SidebarsIdPutRequestWidgetsInner> widgets, final ApiCallback<Sidebar> _callback) throws ApiException {

        okhttp3.Call localVarCall = sidebarsIdPatchValidateBeforeCall(id, widgets, _callback);
        Type localVarReturnType = new TypeToken<Sidebar>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for sidebarsIdPost
     * @param id  (required)
     * @param widgets Nested widgets. (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call sidebarsIdPostCall(@javax.annotation.Nonnull String id, @javax.annotation.Nullable List<SidebarsIdPutRequestWidgetsInner> widgets, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/sidebars/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (widgets != null) {
            localVarFormParams.put("widgets", widgets);
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/x-www-form-urlencoded"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "basicAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call sidebarsIdPostValidateBeforeCall(@javax.annotation.Nonnull String id, @javax.annotation.Nullable List<SidebarsIdPutRequestWidgetsInner> widgets, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling sidebarsIdPost(Async)");
        }

        return sidebarsIdPostCall(id, widgets, _callback);

    }

    /**
     * 
     * 
     * @param id  (required)
     * @param widgets Nested widgets. (optional)
     * @return Sidebar
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public Sidebar sidebarsIdPost(@javax.annotation.Nonnull String id, @javax.annotation.Nullable List<SidebarsIdPutRequestWidgetsInner> widgets) throws ApiException {
        ApiResponse<Sidebar> localVarResp = sidebarsIdPostWithHttpInfo(id, widgets);
        return localVarResp.getData();
    }

    /**
     * 
     * 
     * @param id  (required)
     * @param widgets Nested widgets. (optional)
     * @return ApiResponse&lt;Sidebar&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Sidebar> sidebarsIdPostWithHttpInfo(@javax.annotation.Nonnull String id, @javax.annotation.Nullable List<SidebarsIdPutRequestWidgetsInner> widgets) throws ApiException {
        okhttp3.Call localVarCall = sidebarsIdPostValidateBeforeCall(id, widgets, null);
        Type localVarReturnType = new TypeToken<Sidebar>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * 
     * @param id  (required)
     * @param widgets Nested widgets. (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call sidebarsIdPostAsync(@javax.annotation.Nonnull String id, @javax.annotation.Nullable List<SidebarsIdPutRequestWidgetsInner> widgets, final ApiCallback<Sidebar> _callback) throws ApiException {

        okhttp3.Call localVarCall = sidebarsIdPostValidateBeforeCall(id, widgets, _callback);
        Type localVarReturnType = new TypeToken<Sidebar>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for sidebarsIdPut
     * @param id  (required)
     * @param widgets Nested widgets. (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call sidebarsIdPutCall(@javax.annotation.Nonnull String id, @javax.annotation.Nullable List<SidebarsIdPutRequestWidgetsInner> widgets, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/sidebars/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (widgets != null) {
            localVarFormParams.put("widgets", widgets);
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/x-www-form-urlencoded"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "basicAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call sidebarsIdPutValidateBeforeCall(@javax.annotation.Nonnull String id, @javax.annotation.Nullable List<SidebarsIdPutRequestWidgetsInner> widgets, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling sidebarsIdPut(Async)");
        }

        return sidebarsIdPutCall(id, widgets, _callback);

    }

    /**
     * 
     * 
     * @param id  (required)
     * @param widgets Nested widgets. (optional)
     * @return Sidebar
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public Sidebar sidebarsIdPut(@javax.annotation.Nonnull String id, @javax.annotation.Nullable List<SidebarsIdPutRequestWidgetsInner> widgets) throws ApiException {
        ApiResponse<Sidebar> localVarResp = sidebarsIdPutWithHttpInfo(id, widgets);
        return localVarResp.getData();
    }

    /**
     * 
     * 
     * @param id  (required)
     * @param widgets Nested widgets. (optional)
     * @return ApiResponse&lt;Sidebar&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Sidebar> sidebarsIdPutWithHttpInfo(@javax.annotation.Nonnull String id, @javax.annotation.Nullable List<SidebarsIdPutRequestWidgetsInner> widgets) throws ApiException {
        okhttp3.Call localVarCall = sidebarsIdPutValidateBeforeCall(id, widgets, null);
        Type localVarReturnType = new TypeToken<Sidebar>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * 
     * @param id  (required)
     * @param widgets Nested widgets. (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call sidebarsIdPutAsync(@javax.annotation.Nonnull String id, @javax.annotation.Nullable List<SidebarsIdPutRequestWidgetsInner> widgets, final ApiCallback<Sidebar> _callback) throws ApiException {

        okhttp3.Call localVarCall = sidebarsIdPutValidateBeforeCall(id, widgets, _callback);
        Type localVarReturnType = new TypeToken<Sidebar>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
