/*
 * WordPress REST API
 * The WordPress REST API is a powerful part of WordPress that lets you read and write various parts of WordPress data such as posts, pages, users, media, categories, tags, and custom content types defined in the installation.
 *
 * The version of the OpenAPI document: v2
 * Contact: labs@wtx.pl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pl.wtx.wordpress.api.client;

import pl.wtx.wordpress.api.client.invoker.ApiCallback;
import pl.wtx.wordpress.api.client.invoker.ApiClient;
import pl.wtx.wordpress.api.client.invoker.ApiException;
import pl.wtx.wordpress.api.client.invoker.ApiResponse;
import pl.wtx.wordpress.api.client.invoker.Configuration;
import pl.wtx.wordpress.api.client.invoker.Pair;
import pl.wtx.wordpress.api.client.invoker.ProgressRequestBody;
import pl.wtx.wordpress.api.client.invoker.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import pl.wtx.wordpress.api.client.model.Widget;
import pl.wtx.wordpress.api.client.model.WidgetsPostRequestInstance;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class WidgetsApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public WidgetsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public WidgetsApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for widgetsGet
     * @param context Scope under which the request is made; determines fields present in response. (optional, default to view)
     * @param sidebar The sidebar to return widgets for. (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call widgetsGetCall(@javax.annotation.Nullable String context, @javax.annotation.Nullable String sidebar, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/widgets";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (context != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("context", context));
        }

        if (sidebar != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("sidebar", sidebar));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "basicAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call widgetsGetValidateBeforeCall(@javax.annotation.Nullable String context, @javax.annotation.Nullable String sidebar, final ApiCallback _callback) throws ApiException {
        return widgetsGetCall(context, sidebar, _callback);

    }

    /**
     * 
     * 
     * @param context Scope under which the request is made; determines fields present in response. (optional, default to view)
     * @param sidebar The sidebar to return widgets for. (optional)
     * @return List&lt;Widget&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public List<Widget> widgetsGet(@javax.annotation.Nullable String context, @javax.annotation.Nullable String sidebar) throws ApiException {
        ApiResponse<List<Widget>> localVarResp = widgetsGetWithHttpInfo(context, sidebar);
        return localVarResp.getData();
    }

    /**
     * 
     * 
     * @param context Scope under which the request is made; determines fields present in response. (optional, default to view)
     * @param sidebar The sidebar to return widgets for. (optional)
     * @return ApiResponse&lt;List&lt;Widget&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<Widget>> widgetsGetWithHttpInfo(@javax.annotation.Nullable String context, @javax.annotation.Nullable String sidebar) throws ApiException {
        okhttp3.Call localVarCall = widgetsGetValidateBeforeCall(context, sidebar, null);
        Type localVarReturnType = new TypeToken<List<Widget>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * 
     * @param context Scope under which the request is made; determines fields present in response. (optional, default to view)
     * @param sidebar The sidebar to return widgets for. (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call widgetsGetAsync(@javax.annotation.Nullable String context, @javax.annotation.Nullable String sidebar, final ApiCallback<List<Widget>> _callback) throws ApiException {

        okhttp3.Call localVarCall = widgetsGetValidateBeforeCall(context, sidebar, _callback);
        Type localVarReturnType = new TypeToken<List<Widget>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for widgetsIdDelete
     * @param id  (required)
     * @param force Whether to force removal of the widget, or move it to the inactive sidebar. (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call widgetsIdDeleteCall(@javax.annotation.Nonnull String id, @javax.annotation.Nullable Boolean force, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/widgets/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (force != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("force", force));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "basicAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call widgetsIdDeleteValidateBeforeCall(@javax.annotation.Nonnull String id, @javax.annotation.Nullable Boolean force, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling widgetsIdDelete(Async)");
        }

        return widgetsIdDeleteCall(id, force, _callback);

    }

    /**
     * 
     * 
     * @param id  (required)
     * @param force Whether to force removal of the widget, or move it to the inactive sidebar. (optional)
     * @return Widget
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public Widget widgetsIdDelete(@javax.annotation.Nonnull String id, @javax.annotation.Nullable Boolean force) throws ApiException {
        ApiResponse<Widget> localVarResp = widgetsIdDeleteWithHttpInfo(id, force);
        return localVarResp.getData();
    }

    /**
     * 
     * 
     * @param id  (required)
     * @param force Whether to force removal of the widget, or move it to the inactive sidebar. (optional)
     * @return ApiResponse&lt;Widget&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Widget> widgetsIdDeleteWithHttpInfo(@javax.annotation.Nonnull String id, @javax.annotation.Nullable Boolean force) throws ApiException {
        okhttp3.Call localVarCall = widgetsIdDeleteValidateBeforeCall(id, force, null);
        Type localVarReturnType = new TypeToken<Widget>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * 
     * @param id  (required)
     * @param force Whether to force removal of the widget, or move it to the inactive sidebar. (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call widgetsIdDeleteAsync(@javax.annotation.Nonnull String id, @javax.annotation.Nullable Boolean force, final ApiCallback<Widget> _callback) throws ApiException {

        okhttp3.Call localVarCall = widgetsIdDeleteValidateBeforeCall(id, force, _callback);
        Type localVarReturnType = new TypeToken<Widget>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for widgetsIdGet
     * @param id  (required)
     * @param context Scope under which the request is made; determines fields present in response. (optional, default to view)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call widgetsIdGetCall(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String context, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/widgets/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (context != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("context", context));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "basicAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call widgetsIdGetValidateBeforeCall(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String context, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling widgetsIdGet(Async)");
        }

        return widgetsIdGetCall(id, context, _callback);

    }

    /**
     * 
     * 
     * @param id  (required)
     * @param context Scope under which the request is made; determines fields present in response. (optional, default to view)
     * @return Widget
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public Widget widgetsIdGet(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String context) throws ApiException {
        ApiResponse<Widget> localVarResp = widgetsIdGetWithHttpInfo(id, context);
        return localVarResp.getData();
    }

    /**
     * 
     * 
     * @param id  (required)
     * @param context Scope under which the request is made; determines fields present in response. (optional, default to view)
     * @return ApiResponse&lt;Widget&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Widget> widgetsIdGetWithHttpInfo(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String context) throws ApiException {
        okhttp3.Call localVarCall = widgetsIdGetValidateBeforeCall(id, context, null);
        Type localVarReturnType = new TypeToken<Widget>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * 
     * @param id  (required)
     * @param context Scope under which the request is made; determines fields present in response. (optional, default to view)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call widgetsIdGetAsync(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String context, final ApiCallback<Widget> _callback) throws ApiException {

        okhttp3.Call localVarCall = widgetsIdGetValidateBeforeCall(id, context, _callback);
        Type localVarReturnType = new TypeToken<Widget>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for widgetsIdPatch
     * @param id Unique identifier for the widget. (required)
     * @param idBase The type of the widget. Corresponds to ID in widget-types endpoint. (optional)
     * @param sidebar The sidebar the widget belongs to. (optional)
     * @param instance  (optional)
     * @param formData URL-encoded form data from the widget admin form. Used to update a widget that does not support instance. Write only. (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call widgetsIdPatchCall(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String idBase, @javax.annotation.Nullable String sidebar, @javax.annotation.Nullable WidgetsPostRequestInstance instance, @javax.annotation.Nullable String formData, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/widgets/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (idBase != null) {
            localVarFormParams.put("id_base", idBase);
        }

        if (sidebar != null) {
            localVarFormParams.put("sidebar", sidebar);
        }

        if (instance != null) {
            localVarFormParams.put("instance", instance);
        }

        if (formData != null) {
            localVarFormParams.put("form_data", formData);
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/x-www-form-urlencoded"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "basicAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "PATCH", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call widgetsIdPatchValidateBeforeCall(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String idBase, @javax.annotation.Nullable String sidebar, @javax.annotation.Nullable WidgetsPostRequestInstance instance, @javax.annotation.Nullable String formData, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling widgetsIdPatch(Async)");
        }

        return widgetsIdPatchCall(id, idBase, sidebar, instance, formData, _callback);

    }

    /**
     * 
     * 
     * @param id Unique identifier for the widget. (required)
     * @param idBase The type of the widget. Corresponds to ID in widget-types endpoint. (optional)
     * @param sidebar The sidebar the widget belongs to. (optional)
     * @param instance  (optional)
     * @param formData URL-encoded form data from the widget admin form. Used to update a widget that does not support instance. Write only. (optional)
     * @return Widget
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public Widget widgetsIdPatch(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String idBase, @javax.annotation.Nullable String sidebar, @javax.annotation.Nullable WidgetsPostRequestInstance instance, @javax.annotation.Nullable String formData) throws ApiException {
        ApiResponse<Widget> localVarResp = widgetsIdPatchWithHttpInfo(id, idBase, sidebar, instance, formData);
        return localVarResp.getData();
    }

    /**
     * 
     * 
     * @param id Unique identifier for the widget. (required)
     * @param idBase The type of the widget. Corresponds to ID in widget-types endpoint. (optional)
     * @param sidebar The sidebar the widget belongs to. (optional)
     * @param instance  (optional)
     * @param formData URL-encoded form data from the widget admin form. Used to update a widget that does not support instance. Write only. (optional)
     * @return ApiResponse&lt;Widget&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Widget> widgetsIdPatchWithHttpInfo(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String idBase, @javax.annotation.Nullable String sidebar, @javax.annotation.Nullable WidgetsPostRequestInstance instance, @javax.annotation.Nullable String formData) throws ApiException {
        okhttp3.Call localVarCall = widgetsIdPatchValidateBeforeCall(id, idBase, sidebar, instance, formData, null);
        Type localVarReturnType = new TypeToken<Widget>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * 
     * @param id Unique identifier for the widget. (required)
     * @param idBase The type of the widget. Corresponds to ID in widget-types endpoint. (optional)
     * @param sidebar The sidebar the widget belongs to. (optional)
     * @param instance  (optional)
     * @param formData URL-encoded form data from the widget admin form. Used to update a widget that does not support instance. Write only. (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call widgetsIdPatchAsync(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String idBase, @javax.annotation.Nullable String sidebar, @javax.annotation.Nullable WidgetsPostRequestInstance instance, @javax.annotation.Nullable String formData, final ApiCallback<Widget> _callback) throws ApiException {

        okhttp3.Call localVarCall = widgetsIdPatchValidateBeforeCall(id, idBase, sidebar, instance, formData, _callback);
        Type localVarReturnType = new TypeToken<Widget>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for widgetsIdPost
     * @param id Unique identifier for the widget. (required)
     * @param idBase The type of the widget. Corresponds to ID in widget-types endpoint. (optional)
     * @param sidebar The sidebar the widget belongs to. (optional)
     * @param instance  (optional)
     * @param formData URL-encoded form data from the widget admin form. Used to update a widget that does not support instance. Write only. (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call widgetsIdPostCall(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String idBase, @javax.annotation.Nullable String sidebar, @javax.annotation.Nullable WidgetsPostRequestInstance instance, @javax.annotation.Nullable String formData, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/widgets/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (idBase != null) {
            localVarFormParams.put("id_base", idBase);
        }

        if (sidebar != null) {
            localVarFormParams.put("sidebar", sidebar);
        }

        if (instance != null) {
            localVarFormParams.put("instance", instance);
        }

        if (formData != null) {
            localVarFormParams.put("form_data", formData);
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/x-www-form-urlencoded"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "basicAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call widgetsIdPostValidateBeforeCall(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String idBase, @javax.annotation.Nullable String sidebar, @javax.annotation.Nullable WidgetsPostRequestInstance instance, @javax.annotation.Nullable String formData, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling widgetsIdPost(Async)");
        }

        return widgetsIdPostCall(id, idBase, sidebar, instance, formData, _callback);

    }

    /**
     * 
     * 
     * @param id Unique identifier for the widget. (required)
     * @param idBase The type of the widget. Corresponds to ID in widget-types endpoint. (optional)
     * @param sidebar The sidebar the widget belongs to. (optional)
     * @param instance  (optional)
     * @param formData URL-encoded form data from the widget admin form. Used to update a widget that does not support instance. Write only. (optional)
     * @return Widget
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public Widget widgetsIdPost(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String idBase, @javax.annotation.Nullable String sidebar, @javax.annotation.Nullable WidgetsPostRequestInstance instance, @javax.annotation.Nullable String formData) throws ApiException {
        ApiResponse<Widget> localVarResp = widgetsIdPostWithHttpInfo(id, idBase, sidebar, instance, formData);
        return localVarResp.getData();
    }

    /**
     * 
     * 
     * @param id Unique identifier for the widget. (required)
     * @param idBase The type of the widget. Corresponds to ID in widget-types endpoint. (optional)
     * @param sidebar The sidebar the widget belongs to. (optional)
     * @param instance  (optional)
     * @param formData URL-encoded form data from the widget admin form. Used to update a widget that does not support instance. Write only. (optional)
     * @return ApiResponse&lt;Widget&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Widget> widgetsIdPostWithHttpInfo(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String idBase, @javax.annotation.Nullable String sidebar, @javax.annotation.Nullable WidgetsPostRequestInstance instance, @javax.annotation.Nullable String formData) throws ApiException {
        okhttp3.Call localVarCall = widgetsIdPostValidateBeforeCall(id, idBase, sidebar, instance, formData, null);
        Type localVarReturnType = new TypeToken<Widget>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * 
     * @param id Unique identifier for the widget. (required)
     * @param idBase The type of the widget. Corresponds to ID in widget-types endpoint. (optional)
     * @param sidebar The sidebar the widget belongs to. (optional)
     * @param instance  (optional)
     * @param formData URL-encoded form data from the widget admin form. Used to update a widget that does not support instance. Write only. (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call widgetsIdPostAsync(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String idBase, @javax.annotation.Nullable String sidebar, @javax.annotation.Nullable WidgetsPostRequestInstance instance, @javax.annotation.Nullable String formData, final ApiCallback<Widget> _callback) throws ApiException {

        okhttp3.Call localVarCall = widgetsIdPostValidateBeforeCall(id, idBase, sidebar, instance, formData, _callback);
        Type localVarReturnType = new TypeToken<Widget>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for widgetsIdPut
     * @param id Unique identifier for the widget. (required)
     * @param idBase The type of the widget. Corresponds to ID in widget-types endpoint. (optional)
     * @param sidebar The sidebar the widget belongs to. (optional)
     * @param instance  (optional)
     * @param formData URL-encoded form data from the widget admin form. Used to update a widget that does not support instance. Write only. (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call widgetsIdPutCall(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String idBase, @javax.annotation.Nullable String sidebar, @javax.annotation.Nullable WidgetsPostRequestInstance instance, @javax.annotation.Nullable String formData, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/widgets/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (idBase != null) {
            localVarFormParams.put("id_base", idBase);
        }

        if (sidebar != null) {
            localVarFormParams.put("sidebar", sidebar);
        }

        if (instance != null) {
            localVarFormParams.put("instance", instance);
        }

        if (formData != null) {
            localVarFormParams.put("form_data", formData);
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/x-www-form-urlencoded"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "basicAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call widgetsIdPutValidateBeforeCall(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String idBase, @javax.annotation.Nullable String sidebar, @javax.annotation.Nullable WidgetsPostRequestInstance instance, @javax.annotation.Nullable String formData, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling widgetsIdPut(Async)");
        }

        return widgetsIdPutCall(id, idBase, sidebar, instance, formData, _callback);

    }

    /**
     * 
     * 
     * @param id Unique identifier for the widget. (required)
     * @param idBase The type of the widget. Corresponds to ID in widget-types endpoint. (optional)
     * @param sidebar The sidebar the widget belongs to. (optional)
     * @param instance  (optional)
     * @param formData URL-encoded form data from the widget admin form. Used to update a widget that does not support instance. Write only. (optional)
     * @return Widget
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public Widget widgetsIdPut(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String idBase, @javax.annotation.Nullable String sidebar, @javax.annotation.Nullable WidgetsPostRequestInstance instance, @javax.annotation.Nullable String formData) throws ApiException {
        ApiResponse<Widget> localVarResp = widgetsIdPutWithHttpInfo(id, idBase, sidebar, instance, formData);
        return localVarResp.getData();
    }

    /**
     * 
     * 
     * @param id Unique identifier for the widget. (required)
     * @param idBase The type of the widget. Corresponds to ID in widget-types endpoint. (optional)
     * @param sidebar The sidebar the widget belongs to. (optional)
     * @param instance  (optional)
     * @param formData URL-encoded form data from the widget admin form. Used to update a widget that does not support instance. Write only. (optional)
     * @return ApiResponse&lt;Widget&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Widget> widgetsIdPutWithHttpInfo(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String idBase, @javax.annotation.Nullable String sidebar, @javax.annotation.Nullable WidgetsPostRequestInstance instance, @javax.annotation.Nullable String formData) throws ApiException {
        okhttp3.Call localVarCall = widgetsIdPutValidateBeforeCall(id, idBase, sidebar, instance, formData, null);
        Type localVarReturnType = new TypeToken<Widget>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * 
     * @param id Unique identifier for the widget. (required)
     * @param idBase The type of the widget. Corresponds to ID in widget-types endpoint. (optional)
     * @param sidebar The sidebar the widget belongs to. (optional)
     * @param instance  (optional)
     * @param formData URL-encoded form data from the widget admin form. Used to update a widget that does not support instance. Write only. (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call widgetsIdPutAsync(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String idBase, @javax.annotation.Nullable String sidebar, @javax.annotation.Nullable WidgetsPostRequestInstance instance, @javax.annotation.Nullable String formData, final ApiCallback<Widget> _callback) throws ApiException {

        okhttp3.Call localVarCall = widgetsIdPutValidateBeforeCall(id, idBase, sidebar, instance, formData, _callback);
        Type localVarReturnType = new TypeToken<Widget>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for widgetsPost
     * @param sidebar The sidebar the widget belongs to. (required)
     * @param id Unique identifier for the widget. (optional)
     * @param idBase The type of the widget. Corresponds to ID in widget-types endpoint. (optional)
     * @param instance  (optional)
     * @param formData URL-encoded form data from the widget admin form. Used to update a widget that does not support instance. Write only. (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call widgetsPostCall(@javax.annotation.Nonnull String sidebar, @javax.annotation.Nullable String id, @javax.annotation.Nullable String idBase, @javax.annotation.Nullable WidgetsPostRequestInstance instance, @javax.annotation.Nullable String formData, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/widgets";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (id != null) {
            localVarFormParams.put("id", id);
        }

        if (idBase != null) {
            localVarFormParams.put("id_base", idBase);
        }

        if (sidebar != null) {
            localVarFormParams.put("sidebar", sidebar);
        }

        if (instance != null) {
            localVarFormParams.put("instance", instance);
        }

        if (formData != null) {
            localVarFormParams.put("form_data", formData);
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/x-www-form-urlencoded"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "basicAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call widgetsPostValidateBeforeCall(@javax.annotation.Nonnull String sidebar, @javax.annotation.Nullable String id, @javax.annotation.Nullable String idBase, @javax.annotation.Nullable WidgetsPostRequestInstance instance, @javax.annotation.Nullable String formData, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'sidebar' is set
        if (sidebar == null) {
            throw new ApiException("Missing the required parameter 'sidebar' when calling widgetsPost(Async)");
        }

        return widgetsPostCall(sidebar, id, idBase, instance, formData, _callback);

    }

    /**
     * 
     * 
     * @param sidebar The sidebar the widget belongs to. (required)
     * @param id Unique identifier for the widget. (optional)
     * @param idBase The type of the widget. Corresponds to ID in widget-types endpoint. (optional)
     * @param instance  (optional)
     * @param formData URL-encoded form data from the widget admin form. Used to update a widget that does not support instance. Write only. (optional)
     * @return Widget
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public Widget widgetsPost(@javax.annotation.Nonnull String sidebar, @javax.annotation.Nullable String id, @javax.annotation.Nullable String idBase, @javax.annotation.Nullable WidgetsPostRequestInstance instance, @javax.annotation.Nullable String formData) throws ApiException {
        ApiResponse<Widget> localVarResp = widgetsPostWithHttpInfo(sidebar, id, idBase, instance, formData);
        return localVarResp.getData();
    }

    /**
     * 
     * 
     * @param sidebar The sidebar the widget belongs to. (required)
     * @param id Unique identifier for the widget. (optional)
     * @param idBase The type of the widget. Corresponds to ID in widget-types endpoint. (optional)
     * @param instance  (optional)
     * @param formData URL-encoded form data from the widget admin form. Used to update a widget that does not support instance. Write only. (optional)
     * @return ApiResponse&lt;Widget&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Widget> widgetsPostWithHttpInfo(@javax.annotation.Nonnull String sidebar, @javax.annotation.Nullable String id, @javax.annotation.Nullable String idBase, @javax.annotation.Nullable WidgetsPostRequestInstance instance, @javax.annotation.Nullable String formData) throws ApiException {
        okhttp3.Call localVarCall = widgetsPostValidateBeforeCall(sidebar, id, idBase, instance, formData, null);
        Type localVarReturnType = new TypeToken<Widget>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * 
     * @param sidebar The sidebar the widget belongs to. (required)
     * @param id Unique identifier for the widget. (optional)
     * @param idBase The type of the widget. Corresponds to ID in widget-types endpoint. (optional)
     * @param instance  (optional)
     * @param formData URL-encoded form data from the widget admin form. Used to update a widget that does not support instance. Write only. (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call widgetsPostAsync(@javax.annotation.Nonnull String sidebar, @javax.annotation.Nullable String id, @javax.annotation.Nullable String idBase, @javax.annotation.Nullable WidgetsPostRequestInstance instance, @javax.annotation.Nullable String formData, final ApiCallback<Widget> _callback) throws ApiException {

        okhttp3.Call localVarCall = widgetsPostValidateBeforeCall(sidebar, id, idBase, instance, formData, _callback);
        Type localVarReturnType = new TypeToken<Widget>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
